name = "Lean2Js"
version = "0.1.0"
srcDir = "lean"
defaultTargets = ["Lean2Js", "checks", "lean2js"]

[[lean_lib]]
name = "Lean2Js"

[[lean_lib]]
name = "checks"
roots = ["Lean2Js.Checks"]

[[lean_exe]]
name = "lean2js"
root = "Main"
supportInterpreter = true
