name = "LeanTs"
version = "0.1.0"
srcDir = "lean"
defaultTargets = ["LeanTs", "checks", "leants"]

[[lean_lib]]
name = "LeanTs"

[[lean_lib]]
name = "checks"
roots = ["LeanTs.Checks"]

[[lean_exe]]
name = "leants"
root = "Main"
supportInterpreter = true
