// Generated by lean2js. Do not edit.

export type Option<T> =
  | { readonly tag: "none" }
  | { readonly tag: "some"; readonly value: T };

export type Result<T, E> =
  | { readonly tag: "ok"; readonly value: T }
  | { readonly tag: "error"; readonly error: E };

export type Role =
  | { readonly tag: "guest" }
  | { readonly tag: "member" }
  | { readonly tag: "admin" };

export type Money = { readonly tag: "Money"; readonly amount: number; readonly currency: string };

export type OrderState =
  | { readonly tag: "draft" }
  | { readonly tag: "placed"; readonly orderId: number }
  | { readonly tag: "shipped"; readonly orderId: number; readonly trackingId: string }
  | { readonly tag: "cancelled"; readonly reason: string };

export type Paginated<T> = { readonly tag: "Paginated"; readonly items: readonly T[]; readonly total: number };

export type Validated<E, A> =
  | { readonly tag: "valid"; readonly value: A }
  | { readonly tag: "invalid"; readonly errors: readonly E[] };

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function add(a: number, b: number): number;

/**
 * Clamps a quantity to at least 1 and at most upper.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function clampQuantity(quantity: number, upper: number): number;

/**
 * The amount of a line item. The quantity is clamped before multiplying, so a negative quantity never
 * makes the amount negative.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function lineTotal(unitPrice: number, quantity: number): number;

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function roleRank(role: Role): number;

/**
 * The amount of every line of an order at one unit price.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function lineTotals(unitPrice: number, quantities: readonly number[]): readonly number[];

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function anyOverLimit(amounts: readonly number[], limit: number): boolean;

/**
 * The first line that breaks the limit. Lines after it are never looked at.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function firstOverLimit(amounts: readonly number[], limit: number): Option<number>;

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function everyLineWithinLimit(amounts: readonly number[], limit: number): boolean;

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function someLineIsFree(amounts: readonly number[]): boolean;

/**
 * One window of a list. A window reaching past the end is refused rather than shortened.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function pageOf(xs: readonly number[], lo: number, hi: number): readonly number[];

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function mostRecentFirst(events: readonly string[]): readonly string[];

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function combinedCart(saved: readonly number[], added: readonly number[]): readonly number[];

/**
 * An out-of-range read traps rather than yielding `undefined`.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function headOr(xs: readonly number[], fallback: number): number;

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function slugOf(prefix: string, name: string): string;

/**
 * Comparison in code point order. JS's `<` compares UTF-16 units, so it does not agree.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function sortsBefore(a: string, b: string): boolean;

/**
 * Whether a free-text note mentions a search term, ignoring case.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function mentionsTerm(text: string, term: string): boolean;

/**
 * A coupon code as it is stored: the campaign prefix and what the customer typed, upper-cased and with
 * the surrounding whitespace gone.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function storedCoupon(campaign: string, entered: string): string;

/**
 * Whether a coupon belongs to a campaign, comparing the way the codes are stored.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function couponApplies(code: string, campaign: string): boolean;

/**
 * How many columns a line of an uploaded file carries. An empty separator leaves the line whole rather
 * than cutting it into characters.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function fieldCount(row: string, separator: string): number;

/**
 * A label cut to fit, counted in code points so a surrogate pair is never split in half. A negative
 * limit has no string to return and fails the way an out-of-range index does.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function truncateLabel(label: string, limit: number): string;

/**
 * Whether an uploaded file is a spreadsheet, compared the way the names are stored.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function isSpreadsheet(fileName: string): boolean;

/**
 * What a role may do in a day and in a month.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function limitsFor(role: Role): ReadonlyMap<string, number>;

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function priceOf(prices: ReadonlyMap<string, number>, sku: string): Option<number>;

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function isListed(prices: ReadonlyMap<string, number>, sku: string): boolean;

/**
 * The price book after one price change. A sku already in the book keeps its place.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function repriced(prices: ReadonlyMap<string, number>, sku: string, amount: number): ReadonlyMap<string, number>;

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function listedSkus(prices: ReadonlyMap<string, number>): readonly string[];

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function listedPrices(prices: ReadonlyMap<string, number>): readonly number[];

/**
 * The price book after a sku is withdrawn. A sku that was never listed leaves the book unchanged.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function withdrawn(prices: ReadonlyMap<string, number>, sku: string): ReadonlyMap<string, number>;

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function catalogueSize(prices: ReadonlyMap<string, number>): number;

/**
 * Truncating division. Division by zero traps on the JS side too.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function divide(a: number, b: number): number;

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function remainder(a: number, b: number): number;

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function negate(a: number): number;

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function priceGap(a: number, b: number): number;

/**
 * The amount after a percent% discount. The remainder is truncated.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function discounted(amount: number, percent: number): number;

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function tenPercentOff(amount: number): number;

/**
 * Binds the same name twice. ESM runs in strict mode, so emitting `const` twice would fail at import
 * time.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function rebindTwice(amount: number): number;

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function noDiscount(amount: number): number;

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function memberPrice(amount: number): number;

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function guestPrice(amount: number): number;

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function mixChannels(a: number, b: number): number;

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function bucketOf(key: number, buckets: number): number;

/**
 * A channel value held between a floor and a ceiling.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function clampChannel(value: number, lo: number, hi: number): number;

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function scaleFee(fee: bigint, factor: bigint): bigint;

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function bigQuotient(a: bigint, b: bigint): bigint;

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function sameLabel(a: string, b: string): boolean;

/**
 * Doubles as a check on short-circuiting. When `b` is 0 the right-hand side is not evaluated.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function safeQuotientIsPositive(a: number, b: number): boolean;

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function canCheckout(signedIn: boolean, cartTotal: number, stock: number): boolean;

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function cappedCharge(amount: number, budget: number): number;

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function atLeast(amount: number, floor: number): number;

/**
 * Amounts in different currencies cannot be added. `===` is unusable on the JS side, so a structural
 * equality helper is called.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function addMoney(a: Money, b: Money): Result<Money, string>;

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function sameMoney(a: Money, b: Money): boolean;

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function currenciesOf(items: readonly Money[]): readonly string[];

/**
 * Adds the amounts up whatever currency each carries; `addMoney` is the operation that refuses to mix
 * them.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function cartTotal(items: readonly Money[]): number;

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function total(xs: readonly number[]): number;

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function trackingOf(state: OrderState): Option<string>;

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function canRefund(role: Role, state: OrderState): boolean;

/**
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function firstTracking(states: readonly OrderState[]): Option<string>;

/**
 * The orders this role may still refund. The predicate reads `role` from outside the lambda.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function refundableOnly(role: Role, states: readonly OrderState[]): readonly OrderState[];

/**
 * The state transition to shipped. Rejects states that cannot transition and an empty tracking id.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function ship(state: OrderState, trackingId: string): Result<OrderState, string>;

/**
 * The label shown next to a line item.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function quantityLabel(quantity: number): string;

/**
 * Whether a subscription carries on. Both cases are named, so no fallback is needed.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function renewalLabel(autoRenew: boolean): string;

/**
 * An amount of zero is free whatever the currency, and an amount carrying no currency cannot be
 * charged at all.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function chargeable(amount: Money): boolean;

/**
 * The shipping line shown once a transition has been attempted. A draft or cancelled order has nothing
 * to show, so one arm reaches past `ok` and leaves the state itself open.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function settleMessage(outcome: Result<OrderState, string>): string;

/**
 * The order the settlement placed, if it placed one. The wildcard here stands for both the states that
 * are not `placed` and the error, so the split the certificate makes reaches `Except` as well.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function settledOrderId(outcome: Result<OrderState, string>): number;

/**
 * A role with no daily limit recorded may do nothing.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function dailyLimit(role: Role): number;

/**
 * The same read with the arms the other way round: an arm that binds, then a wildcard for the rest.
 * The certificate splits the scrutinee to show the binding arm did not fire, which `Option` needs as much
 * as a type the program declares.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function monthlyLimit(role: Role): number;

/**
 * How many results lie beyond the page in hand.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function remainingItems(page: Paginated<Money>): number;

/**
 * The whole list served as a single page.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function firstPage(amounts: readonly number[]): Paginated<number>;

/**
 * Accepts an order quantity or says why it was refused.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function validateQuantity(quantity: number): Validated<string, number>;

/**
 * The line shown once a quantity has been checked.
 *
 * @throws {Error} whose `code` is `typeError`, `int53Overflow`, `divByZero` or `indexOutOfBounds`.
 */
export declare function validationMessage(outcome: Validated<string, number>): string;
