// Generated by lean2js. Do not edit.

const __fail = (code) => {
  const error = new Error(code);
  error.code = code;
  throw error;
};

// Int53 is a mathematical integer, so no -0 survives. In JS both 0 - 0 and -4 % 2 are -0.
const __i53 = (x) => (Number.isSafeInteger(x) ? ((x === 0) ? 0 : x) : __fail("int53Overflow"));

// Math.trunc(a / b) is off by one when a is near 2^53. Integer division avoids
// floating-point division.
const __i53div = (a, b) => ((b === 0) ? __fail("divByZero") : Number((BigInt(a) / BigInt(b))));

const __i53mod = (a, b) => ((b === 0) ? __fail("divByZero") : __i53((a % b)));

const __u32mul = (a, b) => (Math.imul(a, b) >>> 0);

const __u32div = (a, b) => ((b === 0) ? __fail("divByZero") : (Math.trunc((a / b)) >>> 0));

const __u32mod = (a, b) => ((b === 0) ? __fail("divByZero") : ((a % b) >>> 0));

const __bigdiv = (a, b) => ((b === 0n) ? __fail("divByZero") : (a / b));

const __bigmod = (a, b) => ((b === 0n) ? __fail("divByZero") : (a % b));

// Math.abs, Math.min and Math.max throw on a BigInt, so the comparisons are written out
// instead.
const __abs = (x) => ((x < 0) ? (-x) : x);

const __min = (a, b) => ((a <= b) ? a : b);

const __max = (a, b) => ((a <= b) ? b : a);

// Array.from splits by code point, where indexing a string splits by UTF-16 unit.
const __chars = (s) => Array.from(s);

const __cp = (c) => (c).codePointAt(0);

const __str = (x) => String(x);

// Number() reads "", "0x10" and " 5", and BigInt() throws on anything it dislikes.
// This reads the digits itself and answers only when printing the result back gives the
// string it was handed.
const __toInt = (s) => {
  const xs = __chars(s);
  const neg = (s).startsWith("-");
  const ds = (neg ? (xs).slice(1, (xs).length) : xs);
  let v = 0n;
  for (const c of ds) {
    v = ((v * 10n) + BigInt((__cp(c) - 48)));
  }
  if (((v < 0n) || (v > 9007199254740991n))) {
    return { tag: "none" };
  }
  const n = Number((neg ? (-v) : v));
  if ((String(n) !== s)) {
    return { tag: "none" };
  }
  return { tag: "some", value: n };
};

const __strlen = (s) => (__chars(s)).length;

const __strcmp = (a, b) => {
  const x = __chars(a);
  const y = __chars(b);
  let i = 0;
  for (const c of x) {
    if ((i >= (y).length)) {
      return 1;
    }
    const d = (__cp(c) - __cp((y)[i]));
    if ((d !== 0)) {
      return ((d < 0) ? -1 : 1);
    }
    i = (i + 1);
  }
  return (((x).length === (y).length) ? 0 : -1);
};

// JS's own trim also strips NBSP, the BOM and the line separators; eval strips only these
// four.
const __ws = (c) => ((c === " ") || ((c === "\t") || ((c === "\n") || (c === "\r"))));

const __lead = (xs) => {
  let n = 0;
  for (const c of xs) {
    if ((!__ws(c))) {
      break;
    }
    n = (n + 1);
  }
  return n;
};

const __trim = (s) => {
  const xs = __chars(s);
  const lo = __lead(xs);
  const hi = ((xs).length - __lead(__areverse(xs)));
  return ((xs).slice(lo, hi)).join("");
};

// toUpperCase is not ASCII: it maps "ß" to "SS", changing the length of the
// string.
const __upper = (s) => {
  let out = "";
  for (const c of __chars(s)) {
    out = (out + (((c >= "a") && (c <= "z")) ? (c).toUpperCase() : c));
  }
  return out;
};

const __lower = (s) => {
  let out = "";
  for (const c of __chars(s)) {
    out = (out + (((c >= "A") && (c <= "Z")) ? (c).toLowerCase() : c));
  }
  return out;
};

// Native, unlike the four above: UTF-16 preserves prefixes and suffixes and no argument can
// hold a lone surrogate, so a match on units is a match on code points.
const __startsWith = (s, t) => (s).startsWith(t);

const __endsWith = (s, t) => (s).endsWith(t);

const __includes = (s, t) => (s).includes(t);

// split("") returns the UTF-16 units, where eval returns the whole string.
const __split = (s, sep) => ((sep === "") ? [s] : (s).split(sep));

const __startsAt = (ys, t) => ((ys).join("")).startsWith(t);

// Native indexOf counts UTF-16 units and answers -1 for absence, where this counts code
// points and answers an option.
const __indexOf = (s, t) => {
  const xs = __chars(s);
  let ys = xs;
  let n = 0;
  for (const c of xs) {
    if (__startsAt(ys, t)) {
      break;
    }
    ys = (ys).slice(1, (ys).length);
    n = (n + 1);
  }
  if ((!__startsAt(ys, t))) {
    return { tag: "none" };
  }
  return { tag: "some", value: __i53(n) };
};

const __join = (xs, sep) => {
  if (((xs).length === 0)) {
    return "";
  }
  let out = (xs)[0];
  for (const x of (xs).slice(1, (xs).length)) {
    out = ((out + sep) + x);
  }
  return out;
};

// The bound is divided out rather than the length multiplied up: the product is the thing
// that overflows, and __i53div divides exactly where Math.trunc(a / b) does not.
const __repeat = (s, n) => ((__strlen(s) === 0) ? "" : ((n > __i53div(9007199254740991, __strlen(s))) ? __fail("int53Overflow") : __rep(s, n)));

// Doubling rather than counting: adding one copy at a time would need a loop that runs a
// number of times, and the only loop here runs over an array.
const __rep = (s, n) => {
  if ((n <= 0)) {
    return "";
  }
  const half = __rep((s + s), Math.trunc((n / 2)));
  return (((n % 2) === 1) ? (s + half) : half);
};

// The only loop here runs over an array, so the count becomes an array of that length
// before anything is pushed: __rep builds an n-character string and __chars splits it.
// What is pushed is the length reached so far, which is the index being filled.
const __range = (n) => {
  const out = [];
  for (const c of __chars(__rep("x", n))) {
    out.push((out).length);
  }
  return out;
};

// Indices count code points, and one outside the string fails rather than being clamped.
const __substring = (s, lo, hi) => {
  const xs = __chars(s);
  return ((Number.isSafeInteger(lo) && (Number.isSafeInteger(hi) && ((lo >= 0) && ((hi >= lo) && (hi <= (xs).length))))) ? ((xs).slice(lo, hi)).join("") : __fail("indexOutOfBounds"));
};

// Bounds outside the array fail rather than being clamped, the way an index read does.
const __aslice = (xs, lo, hi) => ((Number.isSafeInteger(lo) && (Number.isSafeInteger(hi) && ((lo >= 0) && ((hi >= lo) && (hi <= (xs).length))))) ? (xs).slice(lo, hi) : __fail("indexOutOfBounds"));

const __aconcat = (a, b) => {
  const out = [];
  for (const v of a) {
    out.push(v);
  }
  for (const v of b) {
    out.push(v);
  }
  return out;
};

// A fresh array: reverse() would otherwise write through to the caller's.
const __areverse = (xs) => {
  const out = [];
  let i = (xs).length;
  for (const v of xs) {
    i = (i - 1);
    out.push((xs)[i]);
  }
  return out;
};

// An out-of-range index fails rather than yielding undefined. undefined does not exist in
// the subset.
const __at = (xs, i) => ((Number.isSafeInteger(i) && ((i >= 0) && (i < (xs).length))) ? (xs)[i] : __fail("indexOutOfBounds"));

const __dget = (d, k) => ((d).has(k) ? { tag: "some", value: (d).get(k) } : { tag: "none" });

const __dhas = (d, k) => (d).has(k);

// A fresh Map: values in the subset are immutable, so set cannot write through to the
// caller's.
const __dset = (d, k, v) => {
  const out = new Map(d);
  out.set(k, v);
  return out;
};

const __dkeys = (d) => Array.from((d).keys());

const __dvalues = (d) => Array.from((d).values());

const __ddelete = (d, k) => {
  const out = new Map();
  for (const key of __dkeys(d)) {
    if ((key !== k)) {
      out.set(key, (d).get(key));
    }
  }
  return out;
};

// === compares references, so it is unusable on constructor values and arrays.
const __eq = (a, b) => {
  if ((a === b)) {
    return true;
  }
  if (((typeof a) !== (typeof b))) {
    return false;
  }
  if (((typeof a) !== "object")) {
    return false;
  }
  if (((a === null) || (b === null))) {
    return false;
  }
  if (((a instanceof Map) || (b instanceof Map))) {
    if ((!((a instanceof Map) && (b instanceof Map)))) {
      return false;
    }
    if (((a).size !== (b).size)) {
      return false;
    }
    const ks = __dkeys(a);
    const ls = __dkeys(b);
    let i = 0;
    for (const key of ks) {
      if (((ls)[i] !== key)) {
        return false;
      }
      if ((!__eq((a).get(key), (b).get(key)))) {
        return false;
      }
      i = (i + 1);
    }
    return true;
  }
  if ((Array.isArray(a) || Array.isArray(b))) {
    if ((!(Array.isArray(a) && Array.isArray(b)))) {
      return false;
    }
    if (((a).length !== (b).length)) {
      return false;
    }
    let i = 0;
    for (const v of a) {
      if ((!__eq(v, (b)[i]))) {
        return false;
      }
      i = (i + 1);
    }
    return true;
  }
  const keys = Object.keys(a);
  if (((keys).length !== (Object.keys(b)).length)) {
    return false;
  }
  for (const key of keys) {
    if ((!Object.hasOwn(b, key))) {
      return false;
    }
    if ((!__eq((a)[key], (b)[key]))) {
      return false;
    }
  }
  return true;
};

const __map = (xs, f) => {
  const out = [];
  for (const v of xs) {
    out.push((f)(v));
  }
  return out;
};

const __filter = (xs, f) => {
  const out = [];
  for (const v of xs) {
    if ((f)(v)) {
      out.push(v);
    }
  }
  return out;
};

// Stops at the first element the predicate accepts, so a predicate that would trap later
// never runs.
const __find = (xs, f) => {
  for (const v of xs) {
    if ((f)(v)) {
      return { tag: "some", value: v };
    }
  }
  return { tag: "none" };
};

const __all = (xs, f) => {
  for (const v of xs) {
    if ((!(f)(v))) {
      return false;
    }
  }
  return true;
};

const __any = (xs, f) => {
  for (const v of xs) {
    if ((f)(v)) {
      return true;
    }
  }
  return false;
};

const __reduce = (xs, init, f) => {
  let acc = init;
  for (const v of xs) {
    acc = (f)(acc, v);
  }
  return acc;
};

// A string goes through __strcmp rather than <=: JS orders strings by UTF-16 unit and the
// subset orders them by code point, which part company on a surrogate pair.
const __keyle = (a, b) => (((typeof a) === "string") ? (__strcmp(a, b) <= 0) : (a <= b));

// One pass with two indices rather than a recursive walk down the tails: the recursion
// would be as deep as the array is long, and a few thousand elements is where a JS engine
// runs out of stack.
// Which side goes first is settled in an expression because the fragment has no else.
const __merge = (xs, ys) => {
  const out = [];
  let i = 0;
  let j = 0;
  for (const _pair of __aconcat(xs, ys)) {
    const left = ((j >= (ys).length) || ((i < (xs).length) && __keyle(((xs)[i])[0], ((ys)[j])[0])));
    out.push((left ? (xs)[i] : (ys)[j]));
    i = (left ? (i + 1) : i);
    j = (left ? j : (j + 1));
  }
  return out;
};

// Splitting into two contiguous halves, the longer one first, is what makes the sort
// stable: equal keys keep the order they came in.
const __msort = (xs) => {
  if (((xs).length <= 1)) {
    return xs;
  }
  const h = Math.trunc((((xs).length + 1) / 2));
  return __merge(__msort((xs).slice(0, h)), __msort((xs).slice(h, (xs).length)));
};

// The key of each element is worked out once, on the way in, rather than at every
// comparison: a key that traps would otherwise do so a number of times the caller cannot
// see.
const __sortBy = (xs, f) => {
  const pairs = [];
  for (const v of xs) {
    pairs.push([(f)(v), v]);
  }
  const sorted = __msort(pairs);
  const out = [];
  for (const pr of sorted) {
    out.push((pr)[1]);
  }
  return out;
};

const __isObj = (x) => (((typeof x) === "object") && ((x !== null) && (!Array.isArray(x))));

// A key the declared type does not name is ignored rather than refused: TypeScript lets a
// value reach a call carrying extra properties, and __ck drops them before the body runs.
const __hasFields = (x, fields, e) => {
  for (const f of fields) {
    if ((!Object.hasOwn(x, (f)[0]))) {
      return false;
    }
    if ((!__has((x)[(f)[0]], (f)[1], e))) {
      return false;
    }
  }
  return true;
};

const __has = (x, t, e) => {
  const k = (t)[0];
  if ((k === "mu")) {
    return __has(x, ["ctors", (t)[1], (t)[2]], __aconcat([[(t)[1], (t)[2]]], e));
  }
  if ((k === "ref")) {
    if (((t)[1] >= (e).length)) {
      return false;
    }
    const b = (e)[(t)[1]];
    return __has(x, ["ctors", (b)[0], (b)[1]], (e).slice((t)[1], (e).length));
  }
  if ((k === "bool")) {
    return ((typeof x) === "boolean");
  }
  if ((k === "int53")) {
    return (((typeof x) === "number") && Number.isSafeInteger(x));
  }
  if ((k === "uint32")) {
    return (((typeof x) === "number") && (Number.isInteger(x) && ((x >= 0) && (x <= 4294967295))));
  }
  if ((k === "string")) {
    return ((typeof x) === "string");
  }
  if ((k === "bigint")) {
    return ((typeof x) === "bigint");
  }
  if ((k === "array")) {
    return (Array.isArray(x) && __all(x, ((y) => __has(y, (t)[1], e))));
  }
  if ((k === "dict")) {
    if ((!(x instanceof Map))) {
      return false;
    }
    if ((!__all(__dkeys(x), ((key) => ((typeof key) === "string"))))) {
      return false;
    }
    return __all(__dvalues(x), ((y) => __has(y, (t)[1], e)));
  }
  if ((!__isObj(x))) {
    return false;
  }
  if ((k === "option")) {
    if (((x).tag === "none")) {
      return __hasFields(x, [], e);
    }
    return (((x).tag === "some") && __hasFields(x, [["value", (t)[1]]], e));
  }
  if ((k === "result")) {
    if (((x).tag === "ok")) {
      return __hasFields(x, [["value", (t)[1]]], e);
    }
    return (((x).tag === "error") && __hasFields(x, [["error", (t)[2]]], e));
  }
  if ((k === "dictObj")) {
    return __all(((x instanceof Map) ? __dvalues(x) : Object.values(x)), ((y) => __has(y, (t)[1], e)));
  }
  const alt = __find((t)[2], ((c) => ((c)[0] === (x)[(t)[1]])));
  return (((alt).tag === "some") && __hasFields(x, ((alt).value)[1], e));
};

const __normFields = (x, key, fields, e) => {
  const out = [[key, (x)[key]]];
  for (const f of fields) {
    if (Object.hasOwn(x, (f)[0])) {
      out.push([(f)[0], __norm((x)[(f)[0]], (f)[1], e)]);
    }
  }
  return Object.fromEntries(out);
};

const __norm = (x, t, e) => {
  const k = (t)[0];
  if ((k === "mu")) {
    return __norm(x, ["ctors", (t)[1], (t)[2]], __aconcat([[(t)[1], (t)[2]]], e));
  }
  if ((k === "ref")) {
    if (((t)[1] >= (e).length)) {
      return x;
    }
    const b = (e)[(t)[1]];
    return __norm(x, ["ctors", (b)[0], (b)[1]], (e).slice((t)[1], (e).length));
  }
  if ((k === "array")) {
    const out = [];
    for (const y of x) {
      out.push(__norm(y, (t)[1], e));
    }
    return out;
  }
  if ((k === "dict")) {
    const out = new Map();
    for (const key of __dkeys(x)) {
      out.set(key, __norm((x).get(key), (t)[1], e));
    }
    return out;
  }
  if ((k === "option")) {
    if (((x).tag === "none")) {
      return __normFields(x, "tag", [], e);
    }
    if (((x).tag === "some")) {
      return __normFields(x, "tag", [["value", (t)[1]]], e);
    }
    return x;
  }
  if ((k === "result")) {
    if (((x).tag === "ok")) {
      return __normFields(x, "tag", [["value", (t)[1]]], e);
    }
    if (((x).tag === "error")) {
      return __normFields(x, "tag", [["error", (t)[2]]], e);
    }
    return x;
  }
  if ((k === "ctors")) {
    const alt = __find((t)[2], ((c) => ((c)[0] === (x)[(t)[1]])));
    if (((alt).tag === "some")) {
      return __normFields(x, (t)[1], ((alt).value)[1], e);
    }
    return x;
  }
  if ((k === "dictObj")) {
    const out = new Map();
    for (const en of ((x instanceof Map) ? Array.from(x) : Object.entries(x))) {
      out.set((en)[0], __norm((en)[1], (t)[1], e));
    }
    return out;
  }
  return x;
};

const __outFields = (x, key, fields, e) => {
  const out = [[key, (x)[key]]];
  for (const f of fields) {
    if (Object.hasOwn(x, (f)[0])) {
      out.push([(f)[0], __out((x)[(f)[0]], (f)[1], e)]);
    }
  }
  return Object.fromEntries(out);
};

const __out = (x, t, e) => {
  const k = (t)[0];
  if ((k === "mu")) {
    return __out(x, ["ctors", (t)[1], (t)[2]], __aconcat([[(t)[1], (t)[2]]], e));
  }
  if ((k === "ref")) {
    if (((t)[1] >= (e).length)) {
      return x;
    }
    const b = (e)[(t)[1]];
    return __out(x, ["ctors", (b)[0], (b)[1]], (e).slice((t)[1], (e).length));
  }
  if ((k === "array")) {
    const out = [];
    for (const y of x) {
      out.push(__out(y, (t)[1], e));
    }
    return out;
  }
  if ((k === "dict")) {
    const out = new Map();
    for (const key of __dkeys(x)) {
      out.set(key, __out((x).get(key), (t)[1], e));
    }
    return out;
  }
  if ((k === "option")) {
    if (((x).tag === "none")) {
      return __outFields(x, "tag", [], e);
    }
    if (((x).tag === "some")) {
      return __outFields(x, "tag", [["value", (t)[1]]], e);
    }
    return x;
  }
  if ((k === "result")) {
    if (((x).tag === "ok")) {
      return __outFields(x, "tag", [["value", (t)[1]]], e);
    }
    if (((x).tag === "error")) {
      return __outFields(x, "tag", [["error", (t)[2]]], e);
    }
    return x;
  }
  if ((k === "ctors")) {
    const alt = __find((t)[2], ((c) => ((c)[0] === (x)[(t)[1]])));
    if (((alt).tag === "some")) {
      return __outFields(x, (t)[1], ((alt).value)[1], e);
    }
    return x;
  }
  if ((k === "dictObj")) {
    if ((!(x instanceof Map))) {
      return x;
    }
    const out = [];
    for (const en of Array.from(x)) {
      out.push([(en)[0], __out((en)[1], (t)[1], e)]);
    }
    return Object.fromEntries(out);
  }
  return x;
};

// Numbers are handed back as they came, unlike __i53: a -0 argument is a safe integer, and
// every answer built from it passes through __i53 or a comparison that already treats -0
// and 0 alike, so normalising one here would change nothing a caller can observe.
// The empty environment is where a walk starts: a type that names itself binds where it is
// expanded, so nothing is in scope before the descriptor is entered.
const __ck = (x, t) => (__has(x, t, []) ? __norm(x, t, []) : __fail("typeError"));

/** add : (a : Int53, b : Int53) → Int53 */
export function add(__p0, __p1) {
  const a = __ck(__p0, ["int53"]);
  const b = __ck(__p1, ["int53"]);
  return __b_add(a, b);
}

function __b_add(a, b) {
  return __i53((a + b));
}

/** clampQuantity : (quantity : Int53, upper : Int53) → Int53 */
export function clampQuantity(__p0, __p1) {
  const quantity = __ck(__p0, ["int53"]);
  const upper = __ck(__p1, ["int53"]);
  return __b_clampQuantity(quantity, upper);
}

function __b_clampQuantity(quantity, upper) {
  return ((quantity < 1) ? 1 : ((quantity > upper) ? upper : quantity));
}

/** lineTotal : (unitPrice : Int53, quantity : Int53) → Int53 */
export function lineTotal(__p0, __p1) {
  const unitPrice = __ck(__p0, ["int53"]);
  const quantity = __ck(__p1, ["int53"]);
  return __b_lineTotal(unitPrice, quantity);
}

function __b_lineTotal(unitPrice, quantity) {
  return __i53((unitPrice * __b_clampQuantity(quantity, 999)));
}

/** roleRank : (role : Role) → Int53 */
export function roleRank(__p0) {
  const role = __ck(__p0, ["ctors", "tag", [["guest", []], ["member", []], ["admin", []]]]);
  return __b_roleRank(role);
}

function __b_roleRank(role) {
  return ((__s) => ((((__s).tag === "guest") ? 0 : (((__s).tag === "member") ? 1 : 2))))(role);
}

/** lineTotals : (unitPrice : Int53, quantities : Array Int53) → Array Int53 */
export function lineTotals(__p0, __p1) {
  const unitPrice = __ck(__p0, ["int53"]);
  const quantities = __ck(__p1, ["array", ["int53"]]);
  return __b_lineTotals(unitPrice, quantities);
}

function __b_lineTotals(unitPrice, quantities) {
  return __map(quantities, (quantity) => (__b_lineTotal(unitPrice, quantity)));
}

/** anyOverLimit : (amounts : Array Int53, limit : Int53) → Bool */
export function anyOverLimit(__p0, __p1) {
  const amounts = __ck(__p0, ["array", ["int53"]]);
  const limit = __ck(__p1, ["int53"]);
  return __b_anyOverLimit(amounts, limit);
}

function __b_anyOverLimit(amounts, limit) {
  return __reduce(amounts, false, (seen, amount) => ((seen ? true : (amount > limit))));
}

/** firstOverLimit : (amounts : Array Int53, limit : Int53) → Option Int53 */
export function firstOverLimit(__p0, __p1) {
  const amounts = __ck(__p0, ["array", ["int53"]]);
  const limit = __ck(__p1, ["int53"]);
  return __b_firstOverLimit(amounts, limit);
}

function __b_firstOverLimit(amounts, limit) {
  return __find(amounts, (amount) => ((amount > limit)));
}

/** everyLineWithinLimit : (amounts : Array Int53, limit : Int53) → Bool */
export function everyLineWithinLimit(__p0, __p1) {
  const amounts = __ck(__p0, ["array", ["int53"]]);
  const limit = __ck(__p1, ["int53"]);
  return __b_everyLineWithinLimit(amounts, limit);
}

function __b_everyLineWithinLimit(amounts, limit) {
  return __all(amounts, (amount) => ((amount <= limit)));
}

/** someLineIsFree : (amounts : Array Int53) → Bool */
export function someLineIsFree(__p0) {
  const amounts = __ck(__p0, ["array", ["int53"]]);
  return __b_someLineIsFree(amounts);
}

function __b_someLineIsFree(amounts) {
  return __any(amounts, (amount) => ((amount === 0)));
}

/** pageOf : (xs : Array Int53, lo : Int53, hi : Int53) → Array Int53 */
export function pageOf(__p0, __p1, __p2) {
  const xs = __ck(__p0, ["array", ["int53"]]);
  const lo = __ck(__p1, ["int53"]);
  const hi = __ck(__p2, ["int53"]);
  return __b_pageOf(xs, lo, hi);
}

function __b_pageOf(xs, lo, hi) {
  return __aslice(xs, lo, hi);
}

/** mostRecentFirst : (events : Array String) → Array String */
export function mostRecentFirst(__p0) {
  const events = __ck(__p0, ["array", ["string"]]);
  return __b_mostRecentFirst(events);
}

function __b_mostRecentFirst(events) {
  return __areverse(events);
}

/** combinedCart : (saved : Array Int53, added : Array Int53) → Array Int53 */
export function combinedCart(__p0, __p1) {
  const saved = __ck(__p0, ["array", ["int53"]]);
  const added = __ck(__p1, ["array", ["int53"]]);
  return __b_combinedCart(saved, added);
}

function __b_combinedCart(saved, added) {
  return __aconcat(saved, added);
}

/** headOr : (xs : Array Int53, fallback : Int53) → Int53 */
export function headOr(__p0, __p1) {
  const xs = __ck(__p0, ["array", ["int53"]]);
  const fallback = __ck(__p1, ["int53"]);
  return __b_headOr(xs, fallback);
}

function __b_headOr(xs, fallback) {
  return ((__i53((xs).length) < 1) ? fallback : __at(xs, 0));
}

/** slugOf : (prefix : String, name : String) → String */
export function slugOf(__p0, __p1) {
  const prefix = __ck(__p0, ["string"]);
  const name = __ck(__p1, ["string"]);
  return __b_slugOf(prefix, name);
}

function __b_slugOf(prefix, name) {
  return ((prefix + "-") + name);
}

/** orderReference : (prefix : String, orderNo : Int53) → String */
export function orderReference(__p0, __p1) {
  const prefix = __ck(__p0, ["string"]);
  const orderNo = __ck(__p1, ["int53"]);
  return __b_orderReference(prefix, orderNo);
}

function __b_orderReference(prefix, orderNo) {
  return ((prefix + "-") + __str(orderNo));
}

/** amountOf : (field : String) → Option Int53 */
export function amountOf(__p0) {
  const field = __ck(__p0, ["string"]);
  return __b_amountOf(field);
}

function __b_amountOf(field) {
  return __toInt(field);
}

/** amountOr : (field : String, fallback : Int53) → Int53 */
export function amountOr(__p0, __p1) {
  const field = __ck(__p0, ["string"]);
  const fallback = __ck(__p1, ["int53"]);
  return __b_amountOr(field, fallback);
}

function __b_amountOr(field, fallback) {
  return ((__s) => ((((__s).tag === "some") ? ((a) => (a))((__s).value) : fallback)))(__toInt(field));
}

/** separatorAt : (reference : String, sep : String) → Option Int53 */
export function separatorAt(__p0, __p1) {
  const reference = __ck(__p0, ["string"]);
  const sep = __ck(__p1, ["string"]);
  return __b_separatorAt(reference, sep);
}

function __b_separatorAt(reference, sep) {
  return __indexOf(reference, sep);
}

/** referencePrefix : (reference : String) → String */
export function referencePrefix(__p0) {
  const reference = __ck(__p0, ["string"]);
  return __b_referencePrefix(reference);
}

function __b_referencePrefix(reference) {
  return ((__s) => ((((__s).tag === "some") ? ((i) => (__substring(reference, 0, i)))((__s).value) : reference)))(__indexOf(reference, "-"));
}

/** joinFields : (fields : Array String, separator : String) → String */
export function joinFields(__p0, __p1) {
  const fields = __ck(__p0, ["array", ["string"]]);
  const separator = __ck(__p1, ["string"]);
  return __b_joinFields(fields, separator);
}

function __b_joinFields(fields, separator) {
  return __join(fields, separator);
}

/** referenceFrom : (parts : Array String) → String */
export function referenceFrom(__p0) {
  const parts = __ck(__p0, ["array", ["string"]]);
  return __b_referenceFrom(parts);
}

function __b_referenceFrom(parts) {
  return __join(parts, "-");
}

/** refiled : (reference : String, oldSep : String, newSep : String) → String */
export function refiled(__p0, __p1, __p2) {
  const reference = __ck(__p0, ["string"]);
  const oldSep = __ck(__p1, ["string"]);
  const newSep = __ck(__p2, ["string"]);
  return __b_refiled(reference, oldSep, newSep);
}

function __b_refiled(reference, oldSep, newSep) {
  return __join(__split(reference, oldSep), newSep);
}

/** receiptRule : (mark : String) → String */
export function receiptRule(__p0) {
  const mark = __ck(__p0, ["string"]);
  return __b_receiptRule(mark);
}

function __b_receiptRule(mark) {
  return __repeat(mark, 32);
}

/** amountColumn : (amount : Int53) → String */
export function amountColumn(__p0) {
  const amount = __ck(__p0, ["int53"]);
  return __b_amountColumn(amount);
}

function __b_amountColumn(amount) {
  return (((__i53(__strlen(" ")) === 0) || (12 <= __i53(__strlen(__str(amount))))) ? __str(amount) : (__substring(__repeat(" ", __i53((12 - __i53(__strlen(__str(amount)))))), 0, __i53((12 - __i53(__strlen(__str(amount)))))) + __str(amount)));
}

/** lineNumbers : (rows : Int53) → Array Int53 */
export function lineNumbers(__p0) {
  const rows = __ck(__p0, ["int53"]);
  return __b_lineNumbers(rows);
}

function __b_lineNumbers(rows) {
  return __map(__range(__min(__max(rows, 0), 999)), (i) => (__i53((i + 1))));
}

/** sortsBefore : (a : String, b : String) → Bool */
export function sortsBefore(__p0, __p1) {
  const a = __ck(__p0, ["string"]);
  const b = __ck(__p1, ["string"]);
  return __b_sortsBefore(a, b);
}

function __b_sortsBefore(a, b) {
  return (__strcmp(a, b) < 0);
}

/** mentionsTerm : (text : String, term : String) → Bool */
export function mentionsTerm(__p0, __p1) {
  const text = __ck(__p0, ["string"]);
  const term = __ck(__p1, ["string"]);
  return __b_mentionsTerm(text, term);
}

function __b_mentionsTerm(text, term) {
  return __includes(__lower(text), __lower(term));
}

/** storedCoupon : (campaign : String, entered : String) → String */
export function storedCoupon(__p0, __p1) {
  const campaign = __ck(__p0, ["string"]);
  const entered = __ck(__p1, ["string"]);
  return __b_storedCoupon(campaign, entered);
}

function __b_storedCoupon(campaign, entered) {
  return __upper(__trim((campaign + entered)));
}

/** comparable : (s : String) → String */
function comparable(__p0) {
  const s = __ck(__p0, ["string"]);
  return __b_comparable(s);
}

function __b_comparable(s) {
  return __lower(__trim(s));
}

/** couponApplies : (code : String, campaign : String) → Bool */
export function couponApplies(__p0, __p1) {
  const code = __ck(__p0, ["string"]);
  const campaign = __ck(__p1, ["string"]);
  return __b_couponApplies(code, campaign);
}

function __b_couponApplies(code, campaign) {
  return __startsWith(__b_comparable(code), __b_comparable(campaign));
}

/** fieldCount : (row : String, separator : String) → Int53 */
export function fieldCount(__p0, __p1) {
  const row = __ck(__p0, ["string"]);
  const separator = __ck(__p1, ["string"]);
  return __b_fieldCount(row, separator);
}

function __b_fieldCount(row, separator) {
  return __i53((__split(row, separator)).length);
}

/** truncateLabel : (label : String, limit : Int53) → String */
export function truncateLabel(__p0, __p1) {
  const label = __ck(__p0, ["string"]);
  const limit = __ck(__p1, ["int53"]);
  return __b_truncateLabel(label, limit);
}

function __b_truncateLabel(label, limit) {
  return ((__i53(__strlen(label)) <= limit) ? label : (__substring(label, 0, limit) + "..."));
}

/** isSpreadsheet : (fileName : String) → Bool */
export function isSpreadsheet(__p0) {
  const fileName = __ck(__p0, ["string"]);
  return __b_isSpreadsheet(fileName);
}

function __b_isSpreadsheet(fileName) {
  return __endsWith(__b_comparable(fileName), ".csv");
}

/** limitsFor : (role : Role) → Dict Int53 */
export function limitsFor(__p0) {
  const role = __ck(__p0, ["ctors", "tag", [["guest", []], ["member", []], ["admin", []]]]);
  return __b_limitsFor(role);
}

function __b_limitsFor(role) {
  return ((__s) => ((((__s).tag === "guest") ? new Map([["daily", 10], ["monthly", 100]]) : (((__s).tag === "member") ? new Map([["daily", 100], ["monthly", 3000]]) : new Map([["daily", 1000], ["monthly", 30000]])))))(role);
}

/** priceOf : (prices : Dict Int53, sku : String) → Option Int53 */
export function priceOf(__p0, __p1) {
  const prices = __ck(__p0, ["dict", ["int53"]]);
  const sku = __ck(__p1, ["string"]);
  return __b_priceOf(prices, sku);
}

function __b_priceOf(prices, sku) {
  return __dget(prices, sku);
}

/** isListed : (prices : Dict Int53, sku : String) → Bool */
export function isListed(__p0, __p1) {
  const prices = __ck(__p0, ["dict", ["int53"]]);
  const sku = __ck(__p1, ["string"]);
  return __b_isListed(prices, sku);
}

function __b_isListed(prices, sku) {
  return __dhas(prices, sku);
}

/** repriced : (prices : Dict Int53, sku : String, amount : Int53) → Dict Int53 */
export function repriced(__p0, __p1, __p2) {
  const prices = __ck(__p0, ["dict", ["int53"]]);
  const sku = __ck(__p1, ["string"]);
  const amount = __ck(__p2, ["int53"]);
  return __b_repriced(prices, sku, amount);
}

function __b_repriced(prices, sku, amount) {
  return __dset(prices, sku, amount);
}

/** listedSkus : (prices : Dict Int53) → Array String */
export function listedSkus(__p0) {
  const prices = __ck(__p0, ["dict", ["int53"]]);
  return __b_listedSkus(prices);
}

function __b_listedSkus(prices) {
  return __dkeys(prices);
}

/** listedPrices : (prices : Dict Int53) → Array Int53 */
export function listedPrices(__p0) {
  const prices = __ck(__p0, ["dict", ["int53"]]);
  return __b_listedPrices(prices);
}

function __b_listedPrices(prices) {
  return __dvalues(prices);
}

/** withdrawn : (prices : Dict Int53, sku : String) → Dict Int53 */
export function withdrawn(__p0, __p1) {
  const prices = __ck(__p0, ["dict", ["int53"]]);
  const sku = __ck(__p1, ["string"]);
  return __b_withdrawn(prices, sku);
}

function __b_withdrawn(prices, sku) {
  return __ddelete(prices, sku);
}

/** catalogueSize : (prices : Dict Int53) → Int53 */
export function catalogueSize(__p0) {
  const prices = __ck(__p0, ["dict", ["int53"]]);
  return __b_catalogueSize(prices);
}

function __b_catalogueSize(prices) {
  return __i53((prices).size);
}

/** objPriceOf : (prices : Dict.Obj Int53, sku : String) → Option Int53 */
export function objPriceOf(__p0, __p1) {
  const prices = __ck(__p0, ["dictObj", ["int53"]]);
  const sku = __ck(__p1, ["string"]);
  return __b_objPriceOf(prices, sku);
}

function __b_objPriceOf(prices, sku) {
  return __dget(prices, sku);
}

/** objIsListed : (prices : Dict.Obj Int53, sku : String) → Bool */
export function objIsListed(__p0, __p1) {
  const prices = __ck(__p0, ["dictObj", ["int53"]]);
  const sku = __ck(__p1, ["string"]);
  return __b_objIsListed(prices, sku);
}

function __b_objIsListed(prices, sku) {
  return __dhas(prices, sku);
}

/** objRepriced : (prices : Dict.Obj Int53, sku : String, amount : Int53) → Dict.Obj Int53 */
export function objRepriced(__p0, __p1, __p2) {
  const prices = __ck(__p0, ["dictObj", ["int53"]]);
  const sku = __ck(__p1, ["string"]);
  const amount = __ck(__p2, ["int53"]);
  return __out(__b_objRepriced(prices, sku, amount), ["dictObj", ["int53"]], []);
}

function __b_objRepriced(prices, sku, amount) {
  return __dset(prices, sku, amount);
}

/** objWithdrawn : (prices : Dict.Obj Int53, sku : String) → Dict.Obj Int53 */
export function objWithdrawn(__p0, __p1) {
  const prices = __ck(__p0, ["dictObj", ["int53"]]);
  const sku = __ck(__p1, ["string"]);
  return __out(__b_objWithdrawn(prices, sku), ["dictObj", ["int53"]], []);
}

function __b_objWithdrawn(prices, sku) {
  return __ddelete(prices, sku);
}

/** objListedSkus : (prices : Dict.Obj Int53) → Array String */
export function objListedSkus(__p0) {
  const prices = __ck(__p0, ["dictObj", ["int53"]]);
  return __b_objListedSkus(prices);
}

function __b_objListedSkus(prices) {
  return __dkeys(prices);
}

/** objListedPrices : (prices : Dict.Obj Int53) → Array Int53 */
export function objListedPrices(__p0) {
  const prices = __ck(__p0, ["dictObj", ["int53"]]);
  return __b_objListedPrices(prices);
}

function __b_objListedPrices(prices) {
  return __dvalues(prices);
}

/** objCatalogueSize : (prices : Dict.Obj Int53) → Int53 */
export function objCatalogueSize(__p0) {
  const prices = __ck(__p0, ["dictObj", ["int53"]]);
  return __b_objCatalogueSize(prices);
}

function __b_objCatalogueSize(prices) {
  return __i53((prices).size);
}

/** divide : (a : Int53, b : Int53) → Int53 */
export function divide(__p0, __p1) {
  const a = __ck(__p0, ["int53"]);
  const b = __ck(__p1, ["int53"]);
  return __b_divide(a, b);
}

function __b_divide(a, b) {
  return __i53div(a, b);
}

/** remainder : (a : Int53, b : Int53) → Int53 */
export function remainder(__p0, __p1) {
  const a = __ck(__p0, ["int53"]);
  const b = __ck(__p1, ["int53"]);
  return __b_remainder(a, b);
}

function __b_remainder(a, b) {
  return __i53mod(a, b);
}

/** taxOn : (amount : Int53, rate : Int53) → Int53 */
export function taxOn(__p0, __p1) {
  const amount = __ck(__p0, ["int53"]);
  const rate = __ck(__p1, ["int53"]);
  return __b_taxOn(amount, rate);
}

function __b_taxOn(amount, rate) {
  const q = __i53div(__i53((amount * rate)), 10000);
  const rest = __i53(__abs(__i53mod(__i53((amount * rate)), 10000)));
  return ((rest < __i53((__i53(__abs(10000)) - rest))) ? q : ((__i53((amount * rate)) < 0) ? ((10000 < 0) ? __i53((q + 1)) : __i53((q - 1))) : ((10000 < 0) ? __i53((q - 1)) : __i53((q + 1)))));
}

/** shareOf : (cost : Int53, parties : Int53) → Int53 */
export function shareOf(__p0, __p1) {
  const cost = __ck(__p0, ["int53"]);
  const parties = __ck(__p1, ["int53"]);
  return __b_shareOf(cost, parties);
}

function __b_shareOf(cost, parties) {
  const q = __i53div(cost, __max(parties, 1));
  return ((__i53mod(cost, __max(parties, 1)) === 0) ? q : ((cost < 0) ? ((__max(parties, 1) < 0) ? __i53((q + 1)) : q) : ((__max(parties, 1) < 0) ? q : __i53((q + 1)))));
}

/** evenShare : (amount : Int53, parties : Int53) → Int53 */
export function evenShare(__p0, __p1) {
  const amount = __ck(__p0, ["int53"]);
  const parties = __ck(__p1, ["int53"]);
  return __b_evenShare(amount, parties);
}

function __b_evenShare(amount, parties) {
  const q = __i53div(amount, __max(parties, 1));
  const rest = __i53(__abs(__i53mod(amount, __max(parties, 1))));
  return ((rest < __i53((__i53(__abs(__max(parties, 1))) - rest))) ? q : ((amount < 0) ? ((__max(parties, 1) < 0) ? __i53((q + 1)) : __i53((q - 1))) : ((__max(parties, 1) < 0) ? __i53((q - 1)) : __i53((q + 1)))));
}

/** dayOfInstant : (ms : Int53) → Int53 */
export function dayOfInstant(__p0) {
  const ms = __ck(__p0, ["int53"]);
  return __b_dayOfInstant(ms);
}

function __b_dayOfInstant(ms) {
  const q = __i53div(ms, 86400000);
  return ((__i53mod(ms, 86400000) === 0) ? q : ((ms < 0) ? ((86400000 < 0) ? q : __i53((q - 1))) : ((86400000 < 0) ? __i53((q - 1)) : q)));
}

/** dayNumber : (year : Int53, month : Int53, day : Int53) → Int53 */
export function dayNumber(__p0, __p1, __p2) {
  const year = __ck(__p0, ["int53"]);
  const month = __ck(__p1, ["int53"]);
  const day = __ck(__p2, ["int53"]);
  return __b_dayNumber(year, month, day);
}

function __b_dayNumber(year, month, day) {
  const y = ((month <= 2) ? __i53((year - 1)) : year);
  const era = __i53div(((y >= 0) ? y : __i53((y - 399))), 400);
  const yoe = __i53((y - __i53((era * 400))));
  const doy = __i53((__i53((__i53div(__i53((__i53((153 * __i53((month + ((month > 2) ? -3 : 9))))) + 2)), 5) + day)) - 1));
  const doe = __i53((__i53((__i53((__i53((yoe * 365)) + __i53div(yoe, 4))) - __i53div(yoe, 100))) + doy));
  return __i53((__i53((__i53((era * 146097)) + doe)) - 719468));
}

/** yearOf : (days : Int53) → Int53 */
export function yearOf(__p0) {
  const days = __ck(__p0, ["int53"]);
  return __b_yearOf(days);
}

function __b_yearOf(days) {
  const doy = ((yoe) => (__i53((((z) => (__i53((z - __i53((__i53div(((z >= 0) ? z : __i53((z - 146096))), 146097) * 146097))))))(__i53((days + 719468))) - __i53((__i53((__i53((365 * yoe)) + __i53div(yoe, 4))) - __i53div(yoe, 100)))))))(((doe) => (__i53div(__i53((__i53((__i53((doe - __i53div(doe, 1460))) + __i53div(doe, 36524))) - __i53div(doe, 146096))), 365)))(((z) => (__i53((z - __i53((__i53div(((z >= 0) ? z : __i53((z - 146096))), 146097) * 146097))))))(__i53((days + 719468)))));
  return __i53((__i53((((doe) => (__i53div(__i53((__i53((__i53((doe - __i53div(doe, 1460))) + __i53div(doe, 36524))) - __i53div(doe, 146096))), 365)))(((z) => (__i53((z - __i53((__i53div(((z >= 0) ? z : __i53((z - 146096))), 146097) * 146097))))))(__i53((days + 719468)))) + __i53((((z) => (__i53div(((z >= 0) ? z : __i53((z - 146096))), 146097)))(__i53((days + 719468))) * 400)))) + ((__i53div(__i53((__i53((5 * doy)) + 2)), 153) >= 10) ? 1 : 0)));
}

/** monthOf : (days : Int53) → Int53 */
export function monthOf(__p0) {
  const days = __ck(__p0, ["int53"]);
  return __b_monthOf(days);
}

function __b_monthOf(days) {
  const mp = __i53div(__i53((__i53((5 * ((yoe) => (__i53((((z) => (__i53((z - __i53((__i53div(((z >= 0) ? z : __i53((z - 146096))), 146097) * 146097))))))(__i53((days + 719468))) - __i53((__i53((__i53((365 * yoe)) + __i53div(yoe, 4))) - __i53div(yoe, 100)))))))(((doe) => (__i53div(__i53((__i53((__i53((doe - __i53div(doe, 1460))) + __i53div(doe, 36524))) - __i53div(doe, 146096))), 365)))(((z) => (__i53((z - __i53((__i53div(((z >= 0) ? z : __i53((z - 146096))), 146097) * 146097))))))(__i53((days + 719468))))))) + 2)), 153);
  return __i53((mp + ((mp < 10) ? 3 : -9)));
}

/** dayOfMonthOf : (days : Int53) → Int53 */
export function dayOfMonthOf(__p0) {
  const days = __ck(__p0, ["int53"]);
  return __b_dayOfMonthOf(days);
}

function __b_dayOfMonthOf(days) {
  const doy = ((yoe) => (__i53((((z) => (__i53((z - __i53((__i53div(((z >= 0) ? z : __i53((z - 146096))), 146097) * 146097))))))(__i53((days + 719468))) - __i53((__i53((__i53((365 * yoe)) + __i53div(yoe, 4))) - __i53div(yoe, 100)))))))(((doe) => (__i53div(__i53((__i53((__i53((doe - __i53div(doe, 1460))) + __i53div(doe, 36524))) - __i53div(doe, 146096))), 365)))(((z) => (__i53((z - __i53((__i53div(((z >= 0) ? z : __i53((z - 146096))), 146097) * 146097))))))(__i53((days + 719468)))));
  return __i53((__i53((doy - __i53div(__i53((__i53((153 * __i53div(__i53((__i53((5 * doy)) + 2)), 153))) + 2)), 5))) + 1));
}

/** weekdayOf : (days : Int53) → Int53 */
export function weekdayOf(__p0) {
  const days = __ck(__p0, ["int53"]);
  return __b_weekdayOf(days);
}

function __b_weekdayOf(days) {
  return __i53((__i53((days + 4)) - __i53((7 * ((q) => (((__i53mod(__i53((days + 4)), 7) === 0) ? q : ((__i53((days + 4)) < 0) ? ((7 < 0) ? q : __i53((q - 1))) : ((7 < 0) ? __i53((q - 1)) : q)))))(__i53div(__i53((days + 4)), 7))))));
}

/** monthLength : (year : Int53, month : Int53) → Int53 */
export function monthLength(__p0, __p1) {
  const year = __ck(__p0, ["int53"]);
  const month = __ck(__p1, ["int53"]);
  return __b_monthLength(year, month);
}

function __b_monthLength(year, month) {
  return __i53((((y) => (((era) => (((yoe) => (((doy) => (((doe) => (__i53((__i53((__i53((era * 146097)) + doe)) - 719468))))(__i53((__i53((__i53((__i53((yoe * 365)) + __i53div(yoe, 4))) - __i53div(yoe, 100))) + doy)))))(__i53((__i53((__i53div(__i53((__i53((153 * __i53((((month >= 12) ? 1 : __i53((month + 1))) + ((((month >= 12) ? 1 : __i53((month + 1))) > 2) ? -3 : 9))))) + 2)), 5) + 1)) - 1)))))(__i53((y - __i53((era * 400)))))))(__i53div(((y >= 0) ? y : __i53((y - 399))), 400))))(((((month >= 12) ? 1 : __i53((month + 1))) <= 2) ? __i53((((month >= 12) ? __i53((year + 1)) : year) - 1)) : ((month >= 12) ? __i53((year + 1)) : year))) - ((y) => (((era) => (((yoe) => (((doy) => (((doe) => (__i53((__i53((__i53((era * 146097)) + doe)) - 719468))))(__i53((__i53((__i53((__i53((yoe * 365)) + __i53div(yoe, 4))) - __i53div(yoe, 100))) + doy)))))(__i53((__i53((__i53div(__i53((__i53((153 * __i53((month + ((month > 2) ? -3 : 9))))) + 2)), 5) + 1)) - 1)))))(__i53((y - __i53((era * 400)))))))(__i53div(((y >= 0) ? y : __i53((y - 399))), 400))))(((month <= 2) ? __i53((year - 1)) : year))));
}

/** negate : (a : Int53) → Int53 */
export function negate(__p0) {
  const a = __ck(__p0, ["int53"]);
  return __b_negate(a);
}

function __b_negate(a) {
  return __i53((-a));
}

/** priceGap : (a : Int53, b : Int53) → Int53 */
export function priceGap(__p0, __p1) {
  const a = __ck(__p0, ["int53"]);
  const b = __ck(__p1, ["int53"]);
  return __b_priceGap(a, b);
}

function __b_priceGap(a, b) {
  return __i53(__abs(__i53((a - b))));
}

/** discounted : (amount : Int53, percent : Int53) → Int53 */
export function discounted(__p0, __p1) {
  const amount = __ck(__p0, ["int53"]);
  const percent = __ck(__p1, ["int53"]);
  return __b_discounted(amount, percent);
}

function __b_discounted(amount, percent) {
  const rate = __i53((100 - ((percent < 0) ? 0 : ((percent > 100) ? 100 : percent))));
  return __i53div(__i53((amount * rate)), 100);
}

/** tenPercentOff : (amount : Int53) → Int53 */
export function tenPercentOff(__p0) {
  const amount = __ck(__p0, ["int53"]);
  return __b_tenPercentOff(amount);
}

function __b_tenPercentOff(amount) {
  return __i53((amount - __i53div(amount, 10)));
}

/** rebindTwice : (amount : Int53) → Int53 */
export function rebindTwice(__p0) {
  const amount = __ck(__p0, ["int53"]);
  return __b_rebindTwice(amount);
}

function __b_rebindTwice(amount) {
  return ((amount) => (((amount) => (amount))(__i53((amount * 2)))))(__i53((amount + 1)));
}

/** noDiscount : (amount : Int53) → Int53 */
export function noDiscount(__p0) {
  const amount = __ck(__p0, ["int53"]);
  return __b_noDiscount(amount);
}

function __b_noDiscount(amount) {
  return amount;
}

/** priced : (rule : (Int53) => Int53, amount : Int53) → Int53 */
function priced(__p0, __p1) {
  const rule = __p0;
  const amount = __ck(__p1, ["int53"]);
  return __b_priced(rule, amount);
}

function __b_priced(rule, amount) {
  return __ck(rule(amount), ["int53"]);
}

/** memberPrice : (amount : Int53) → Int53 */
export function memberPrice(__p0) {
  const amount = __ck(__p0, ["int53"]);
  return __b_memberPrice(amount);
}

function __b_memberPrice(amount) {
  return __b_priced(tenPercentOff, amount);
}

/** guestPrice : (amount : Int53) → Int53 */
export function guestPrice(__p0) {
  const amount = __ck(__p0, ["int53"]);
  return __b_guestPrice(amount);
}

function __b_guestPrice(amount) {
  return __b_priced(noDiscount, amount);
}

/** mixChannels : (a : UInt32, b : UInt32) → UInt32 */
export function mixChannels(__p0, __p1) {
  const a = __ck(__p0, ["uint32"]);
  const b = __ck(__p1, ["uint32"]);
  return __b_mixChannels(a, b);
}

function __b_mixChannels(a, b) {
  return ((__u32mul(a, b) + ((a - b) >>> 0)) >>> 0);
}

/** bucketOf : (key : UInt32, buckets : UInt32) → UInt32 */
export function bucketOf(__p0, __p1) {
  const key = __ck(__p0, ["uint32"]);
  const buckets = __ck(__p1, ["uint32"]);
  return __b_bucketOf(key, buckets);
}

function __b_bucketOf(key, buckets) {
  return __u32mod(key, buckets);
}

/** clampChannel : (value : UInt32, lo : UInt32, hi : UInt32) → UInt32 */
export function clampChannel(__p0, __p1, __p2) {
  const value = __ck(__p0, ["uint32"]);
  const lo = __ck(__p1, ["uint32"]);
  const hi = __ck(__p2, ["uint32"]);
  return __b_clampChannel(value, lo, hi);
}

function __b_clampChannel(value, lo, hi) {
  return __min(__max(value, lo), hi);
}

/** scaleFee : (fee : BigInt, factor : BigInt) → BigInt */
export function scaleFee(__p0, __p1) {
  const fee = __ck(__p0, ["bigint"]);
  const factor = __ck(__p1, ["bigint"]);
  return __b_scaleFee(fee, factor);
}

function __b_scaleFee(fee, factor) {
  return ((fee * factor) - 1n);
}

/** bigQuotient : (a : BigInt, b : BigInt) → BigInt */
export function bigQuotient(__p0, __p1) {
  const a = __ck(__p0, ["bigint"]);
  const b = __ck(__p1, ["bigint"]);
  return __b_bigQuotient(a, b);
}

function __b_bigQuotient(a, b) {
  return __bigdiv(a, b);
}

/** sameLabel : (a : String, b : String) → Bool */
export function sameLabel(__p0, __p1) {
  const a = __ck(__p0, ["string"]);
  const b = __ck(__p1, ["string"]);
  return __b_sameLabel(a, b);
}

function __b_sameLabel(a, b) {
  return (a === b);
}

/** safeQuotientIsPositive : (a : Int53, b : Int53) → Bool */
export function safeQuotientIsPositive(__p0, __p1) {
  const a = __ck(__p0, ["int53"]);
  const b = __ck(__p1, ["int53"]);
  return __b_safeQuotientIsPositive(a, b);
}

function __b_safeQuotientIsPositive(a, b) {
  return ((b !== 0) && (__i53div(a, b) > 0));
}

/** canCheckout : (signedIn : Bool, cartTotal : Int53, stock : Int53) → Bool */
export function canCheckout(__p0, __p1, __p2) {
  const signedIn = __ck(__p0, ["bool"]);
  const cartTotal = __ck(__p1, ["int53"]);
  const stock = __ck(__p2, ["int53"]);
  return __b_canCheckout(signedIn, cartTotal, stock);
}

function __b_canCheckout(signedIn, cartTotal, stock) {
  return ((signedIn && (cartTotal > 0)) && (stock >= 1));
}

/** cappedCharge : (amount : Int53, budget : Int53) → Int53 */
export function cappedCharge(__p0, __p1) {
  const amount = __ck(__p0, ["int53"]);
  const budget = __ck(__p1, ["int53"]);
  return __b_cappedCharge(amount, budget);
}

function __b_cappedCharge(amount, budget) {
  return __min(amount, budget);
}

/** atLeast : (amount : Int53, floor : Int53) → Int53 */
export function atLeast(__p0, __p1) {
  const amount = __ck(__p0, ["int53"]);
  const floor = __ck(__p1, ["int53"]);
  return __b_atLeast(amount, floor);
}

function __b_atLeast(amount, floor) {
  return __max(amount, floor);
}

/** addMoney : (a : Money, b : Money) → Result Money String */
export function addMoney(__p0, __p1) {
  const a = __ck(__p0, ["ctors", "tag", [["Money", [["amount", ["int53"]], ["currency", ["string"]]]]]]);
  const b = __ck(__p1, ["ctors", "tag", [["Money", [["amount", ["int53"]], ["currency", ["string"]]]]]]);
  return __b_addMoney(a, b);
}

function __b_addMoney(a, b) {
  return (((a).currency !== (b).currency) ? { "tag": "error", "error": "currency mismatch" } : { "tag": "ok", "value": { "tag": "Money", "amount": __i53(((a).amount + (b).amount)), "currency": (a).currency } });
}

/** sameMoney : (a : Money, b : Money) → Bool */
export function sameMoney(__p0, __p1) {
  const a = __ck(__p0, ["ctors", "tag", [["Money", [["amount", ["int53"]], ["currency", ["string"]]]]]]);
  const b = __ck(__p1, ["ctors", "tag", [["Money", [["amount", ["int53"]], ["currency", ["string"]]]]]]);
  return __b_sameMoney(a, b);
}

function __b_sameMoney(a, b) {
  return __eq(a, b);
}

/** currenciesOf : (items : Array Money) → Array String */
export function currenciesOf(__p0) {
  const items = __ck(__p0, ["array", ["ctors", "tag", [["Money", [["amount", ["int53"]], ["currency", ["string"]]]]]]]);
  return __b_currenciesOf(items);
}

function __b_currenciesOf(items) {
  return __map(items, (item) => ((item).currency));
}

/** cartTotal : (items : Array Money) → Int53 */
export function cartTotal(__p0) {
  const items = __ck(__p0, ["array", ["ctors", "tag", [["Money", [["amount", ["int53"]], ["currency", ["string"]]]]]]]);
  return __b_cartTotal(items);
}

function __b_cartTotal(items) {
  return __reduce(items, 0, (subtotal, item) => (__i53((subtotal + (item).amount))));
}

/** cheapestFirst : (items : Array Money) → Array Money */
export function cheapestFirst(__p0) {
  const items = __ck(__p0, ["array", ["ctors", "tag", [["Money", [["amount", ["int53"]], ["currency", ["string"]]]]]]]);
  return __b_cheapestFirst(items);
}

function __b_cheapestFirst(items) {
  return __sortBy(items, (item) => ((item).amount));
}

/** inLabelOrder : (labels : Array String) → Array String */
export function inLabelOrder(__p0) {
  const labels = __ck(__p0, ["array", ["string"]]);
  return __b_inLabelOrder(labels);
}

function __b_inLabelOrder(labels) {
  return __sortBy(labels, (label) => (label));
}

/** total : (xs : Array Int53) → Int53 */
export function total(__p0) {
  const xs = __ck(__p0, ["array", ["int53"]]);
  return __b_total(xs);
}

function __b_total(xs) {
  return __reduce(xs, 0, (sum, x) => (__i53((sum + x))));
}

/** trackingOf : (state : OrderState) → Option String */
export function trackingOf(__p0) {
  const state = __ck(__p0, ["ctors", "kind", [["draft", []], ["placed", [["orderId", ["int53"]]]], ["shipped", [["orderId", ["int53"]], ["trackingId", ["string"]]]], ["cancelled", [["reason", ["string"]]]]]]);
  return __b_trackingOf(state);
}

function __b_trackingOf(state) {
  return ((__s) => ((((__s).kind === "draft") ? { "tag": "none" } : (((__s).kind === "placed") ? { "tag": "none" } : (((__s).kind === "shipped") ? ((trackingId) => ({ "tag": "some", "value": trackingId }))((__s).trackingId) : { "tag": "none" })))))(state);
}

/** canRefund : (role : Role, state : OrderState) → Bool */
export function canRefund(__p0, __p1) {
  const role = __ck(__p0, ["ctors", "tag", [["guest", []], ["member", []], ["admin", []]]]);
  const state = __ck(__p1, ["ctors", "kind", [["draft", []], ["placed", [["orderId", ["int53"]]]], ["shipped", [["orderId", ["int53"]], ["trackingId", ["string"]]]], ["cancelled", [["reason", ["string"]]]]]]);
  return __b_canRefund(role, state);
}

function __b_canRefund(role, state) {
  return ((__s) => ((((__s).kind === "draft") ? false : (((__s).kind === "placed") ? (__b_roleRank(role) >= 1) : (((__s).kind === "shipped") ? (__b_roleRank(role) >= 2) : false)))))(state);
}

/** firstTracking : (states : Array OrderState) → Option String */
export function firstTracking(__p0) {
  const states = __ck(__p0, ["array", ["ctors", "kind", [["draft", []], ["placed", [["orderId", ["int53"]]]], ["shipped", [["orderId", ["int53"]], ["trackingId", ["string"]]]], ["cancelled", [["reason", ["string"]]]]]]]);
  return __b_firstTracking(states);
}

function __b_firstTracking(states) {
  return ((__i53((states).length) === 0) ? { "tag": "none" } : __b_trackingOf(__at(states, 0)));
}

/** refundableOnly : (role : Role, states : Array OrderState) → Array OrderState */
export function refundableOnly(__p0, __p1) {
  const role = __ck(__p0, ["ctors", "tag", [["guest", []], ["member", []], ["admin", []]]]);
  const states = __ck(__p1, ["array", ["ctors", "kind", [["draft", []], ["placed", [["orderId", ["int53"]]]], ["shipped", [["orderId", ["int53"]], ["trackingId", ["string"]]]], ["cancelled", [["reason", ["string"]]]]]]]);
  return __b_refundableOnly(role, states);
}

function __b_refundableOnly(role, states) {
  return __filter(states, (state) => (__b_canRefund(role, state)));
}

/** ship : (state : OrderState, trackingId : String) → Result OrderState String */
export function ship(__p0, __p1) {
  const state = __ck(__p0, ["ctors", "kind", [["draft", []], ["placed", [["orderId", ["int53"]]]], ["shipped", [["orderId", ["int53"]], ["trackingId", ["string"]]]], ["cancelled", [["reason", ["string"]]]]]]);
  const trackingId = __ck(__p1, ["string"]);
  return __b_ship(state, trackingId);
}

function __b_ship(state, trackingId) {
  return ((__s) => ((((__s).kind === "draft") ? { "tag": "error", "error": "a draft order cannot ship" } : (((__s).kind === "placed") ? ((orderId) => (((trackingId === "") ? { "tag": "error", "error": "a tracking id is required" } : { "tag": "ok", "value": { "kind": "shipped", "orderId": orderId, "trackingId": trackingId } })))((__s).orderId) : (((__s).kind === "shipped") ? { "tag": "error", "error": "the order has already shipped" } : { "tag": "error", "error": "a cancelled order cannot ship" })))))(state);
}

/** quantityLabel : (quantity : Int53) → String */
export function quantityLabel(__p0) {
  const quantity = __ck(__p0, ["int53"]);
  return __b_quantityLabel(quantity);
}

function __b_quantityLabel(quantity) {
  return ((__s) => (((__s === 0) ? "out of stock" : ((__s === 1) ? "last one" : "in stock"))))(quantity);
}

/** renewalLabel : (autoRenew : Bool) → String */
export function renewalLabel(__p0) {
  const autoRenew = __ck(__p0, ["bool"]);
  return __b_renewalLabel(autoRenew);
}

function __b_renewalLabel(autoRenew) {
  return ((__s) => (((__s === true) ? "renews" : "ends")))(autoRenew);
}

/** chargeable : (amount : Money) → Bool */
export function chargeable(__p0) {
  const amount = __ck(__p0, ["ctors", "tag", [["Money", [["amount", ["int53"]], ["currency", ["string"]]]]]]);
  return __b_chargeable(amount);
}

function __b_chargeable(amount) {
  return ((__s) => (((((__s).tag === "Money") && ((__s).amount === 0)) ? false : ((((__s).tag === "Money") && ((__s).currency === "")) ? false : ((value) => ((value > 0)))((__s).amount)))))(amount);
}

/** settleMessage : (outcome : Result OrderState String) → String */
export function settleMessage(__p0) {
  const outcome = __ck(__p0, ["result", ["ctors", "kind", [["draft", []], ["placed", [["orderId", ["int53"]]]], ["shipped", [["orderId", ["int53"]], ["trackingId", ["string"]]]], ["cancelled", [["reason", ["string"]]]]]], ["string"]]);
  return __b_settleMessage(outcome);
}

function __b_settleMessage(outcome) {
  return ((__s) => (((((__s).tag === "ok") && (((__s).value).kind === "shipped")) ? ((trackingId) => (trackingId))(((__s).value).trackingId) : ((((__s).tag === "ok") && (((__s).value).kind === "placed")) ? "awaiting shipment" : (((__s).tag === "ok") ? "no update" : ((message) => (message))((__s).error))))))(outcome);
}

/** settledOrderId : (outcome : Result OrderState String) → Int53 */
export function settledOrderId(__p0) {
  const outcome = __ck(__p0, ["result", ["ctors", "kind", [["draft", []], ["placed", [["orderId", ["int53"]]]], ["shipped", [["orderId", ["int53"]], ["trackingId", ["string"]]]], ["cancelled", [["reason", ["string"]]]]]], ["string"]]);
  return __b_settledOrderId(outcome);
}

function __b_settledOrderId(outcome) {
  return ((__s) => (((((__s).tag === "ok") && (((__s).value).kind === "placed")) ? ((orderId) => (orderId))(((__s).value).orderId) : 0)))(outcome);
}

/** dailyLimit : (role : Role) → Int53 */
export function dailyLimit(__p0) {
  const role = __ck(__p0, ["ctors", "tag", [["guest", []], ["member", []], ["admin", []]]]);
  return __b_dailyLimit(role);
}

function __b_dailyLimit(role) {
  return ((__s) => ((((__s).tag === "some") ? ((value) => (value))((__s).value) : 0)))(__dget(__b_limitsFor(role), "daily"));
}

/** monthlyLimit : (role : Role) → Int53 */
export function monthlyLimit(__p0) {
  const role = __ck(__p0, ["ctors", "tag", [["guest", []], ["member", []], ["admin", []]]]);
  return __b_monthlyLimit(role);
}

function __b_monthlyLimit(role) {
  return ((__s) => ((((__s).tag === "some") ? ((value) => (value))((__s).value) : 0)))(__dget(__b_limitsFor(role), "monthly"));
}

/** remainingItems : (page : Paginated Money) → Int53 */
export function remainingItems(__p0) {
  const page = __ck(__p0, ["ctors", "tag", [["Paginated", [["items", ["array", ["ctors", "tag", [["Money", [["amount", ["int53"]], ["currency", ["string"]]]]]]]], ["total", ["int53"]]]]]]);
  return __b_remainingItems(page);
}

function __b_remainingItems(page) {
  return __i53(((page).total - __i53(((page).items).length)));
}

/** firstPage : (amounts : Array Int53) → Paginated Int53 */
export function firstPage(__p0) {
  const amounts = __ck(__p0, ["array", ["int53"]]);
  return __b_firstPage(amounts);
}

function __b_firstPage(amounts) {
  return { "tag": "Paginated", "items": amounts, "total": __i53((amounts).length) };
}

/** validateQuantity : (quantity : Int53) → Validated String Int53 */
export function validateQuantity(__p0) {
  const quantity = __ck(__p0, ["int53"]);
  return __b_validateQuantity(quantity);
}

function __b_validateQuantity(quantity) {
  return ((quantity < 1) ? { "tag": "invalid", "errors": ["a quantity must be at least 1"] } : ((quantity > 999) ? { "tag": "invalid", "errors": ["a quantity may not exceed 999"] } : { "tag": "valid", "value": quantity }));
}

/** validationMessage : (outcome : Validated String Int53) → String */
export function validationMessage(__p0) {
  const outcome = __ck(__p0, ["ctors", "tag", [["valid", [["value", ["int53"]]]], ["invalid", [["errors", ["array", ["string"]]]]]]]);
  return __b_validationMessage(outcome);
}

function __b_validationMessage(outcome) {
  return ((__s) => ((((__s).tag === "valid") ? ((value) => (__b_quantityLabel(value)))((__s).value) : ((errors) => (((__i53((errors).length) === 0) ? "refused" : __at(errors, 0))))((__s).errors))))(outcome);
}

/** amountWithTax : (amount : Int53) → Array Int53 */
export function amountWithTax(__p0) {
  const amount = __ck(__p0, ["int53"]);
  return __b_amountWithTax(amount);
}

function __b_amountWithTax(amount) {
  return [amount, __i53div(amount, 10)];
}

/** currencyOf : (item : Money) → String */
export function currencyOf(__p0) {
  const item = __ck(__p0, ["ctors", "tag", [["Money", [["amount", ["int53"]], ["currency", ["string"]]]]]]);
  return __b_currencyOf(item);
}

function __b_currencyOf(item) {
  return (item).currency;
}

/** previewLines : (amounts : Array Int53, upTo : Int53) → Array Int53 */
export function previewLines(__p0, __p1) {
  const amounts = __ck(__p0, ["array", ["int53"]]);
  const upTo = __ck(__p1, ["int53"]);
  return __b_previewLines(amounts, upTo);
}

function __b_previewLines(amounts, upTo) {
  return __aslice(amounts, 0, upTo);
}

/** linesBelowFold : (amounts : Array Int53, upTo : Int53) → Array Int53 */
export function linesBelowFold(__p0, __p1) {
  const amounts = __ck(__p0, ["array", ["int53"]]);
  const upTo = __ck(__p1, ["int53"]);
  return __b_linesBelowFold(amounts, upTo);
}

function __b_linesBelowFold(amounts, upTo) {
  return __aslice(amounts, upTo, __i53((amounts).length));
}

/** cartIsEmpty : (items : Array Money) → Bool */
export function cartIsEmpty(__p0) {
  const items = __ck(__p0, ["array", ["ctors", "tag", [["Money", [["amount", ["int53"]], ["currency", ["string"]]]]]]]);
  return __b_cartIsEmpty(items);
}

function __b_cartIsEmpty(items) {
  return (__i53((items).length) === 0);
}

/** stocksSku : (skus : Array String, sku : String) → Bool */
export function stocksSku(__p0, __p1) {
  const skus = __ck(__p0, ["array", ["string"]]);
  const sku = __ck(__p1, ["string"]);
  return __b_stocksSku(skus, sku);
}

function __b_stocksSku(skus, sku) {
  return __any(skus, (y) => ((y === sku)));
}

/** amountsTotal : (amounts : Array Int53) → Int53 */
export function amountsTotal(__p0) {
  const amounts = __ck(__p0, ["array", ["int53"]]);
  return __b_amountsTotal(amounts);
}

function __b_amountsTotal(amounts) {
  return __reduce(amounts, 0, (running, y) => (__i53((running + y))));
}

/** spreadsheetCount : (fileNames : Array String) → Int53 */
export function spreadsheetCount(__p0) {
  const fileNames = __ck(__p0, ["array", ["string"]]);
  return __b_spreadsheetCount(fileNames);
}

function __b_spreadsheetCount(fileNames) {
  return __reduce(fileNames, 0, (running, y) => ((__b_isSpreadsheet(y) ? __i53((running + 1)) : running)));
}

/** firstAmount : (amounts : Array Int53) → Option Int53 */
export function firstAmount(__p0) {
  const amounts = __ck(__p0, ["array", ["int53"]]);
  return __b_firstAmount(amounts);
}

function __b_firstAmount(amounts) {
  return ((__i53((amounts).length) === 0) ? { "tag": "none" } : { "tag": "some", "value": __at(amounts, 0) });
}

/** latestEvent : (events : Array String) → Option String */
export function latestEvent(__p0) {
  const events = __ck(__p0, ["array", ["string"]]);
  return __b_latestEvent(events);
}

function __b_latestEvent(events) {
  return ((__i53((events).length) === 0) ? { "tag": "none" } : { "tag": "some", "value": __at(events, __i53((__i53((events).length) - 1))) });
}

/** allLines : (orders : Array Array Int53) → Array Int53 */
export function allLines(__p0) {
  const orders = __ck(__p0, ["array", ["array", ["int53"]]]);
  return __b_allLines(orders);
}

function __b_allLines(orders) {
  return __reduce(orders, [], (running, xs) => (__aconcat(running, xs)));
}

/** linesWithTax : (amounts : Array Int53) → Array Int53 */
export function linesWithTax(__p0) {
  const amounts = __ck(__p0, ["array", ["int53"]]);
  return __b_linesWithTax(amounts);
}

function __b_linesWithTax(amounts) {
  return __reduce(amounts, [], (running, x) => (__aconcat(running, __b_amountWithTax(x))));
}

/** noteIsBlank : (note : String) → Bool */
export function noteIsBlank(__p0) {
  const note = __ck(__p0, ["string"]);
  return __b_noteIsBlank(note);
}

function __b_noteIsBlank(note) {
  return (__i53(__strlen(__trim(note))) === 0);
}

/** priceOr : (prices : Dict Int53, sku : String, fallback : Int53) → Int53 */
export function priceOr(__p0, __p1, __p2) {
  const prices = __ck(__p0, ["dict", ["int53"]]);
  const sku = __ck(__p1, ["string"]);
  const fallback = __ck(__p2, ["int53"]);
  return __b_priceOr(prices, sku, fallback);
}

function __b_priceOr(prices, sku, fallback) {
  return ((__s) => ((((__s).tag === "some") ? ((a) => (a))((__s).value) : fallback)))(__dget(prices, sku));
}

/** byCurrency : (items : Array Money) → Dict Money */
export function byCurrency(__p0) {
  const items = __ck(__p0, ["array", ["ctors", "tag", [["Money", [["amount", ["int53"]], ["currency", ["string"]]]]]]]);
  return __b_byCurrency(items);
}

function __b_byCurrency(items) {
  return __reduce(items, new Map([]), (d, x) => (__dset(d, __b_currencyOf(x), x)));
}

/** quantityOr : (quantity : Option Int53, fallback : Int53) → Int53 */
export function quantityOr(__p0, __p1) {
  const quantity = __ck(__p0, ["option", ["int53"]]);
  const fallback = __ck(__p1, ["int53"]);
  return __b_quantityOr(quantity, fallback);
}

function __b_quantityOr(quantity, fallback) {
  return ((__s) => ((((__s).tag === "some") ? ((a) => (a))((__s).value) : fallback)))(quantity);
}

/** discountedIfAny : (amount : Option Int53) → Option Int53 */
export function discountedIfAny(__p0) {
  const amount = __ck(__p0, ["option", ["int53"]]);
  return __b_discountedIfAny(amount);
}

function __b_discountedIfAny(amount) {
  return ((__s) => ((((__s).tag === "some") ? ((a) => ({ "tag": "some", "value": __b_tenPercentOff(a) }))((__s).value) : { "tag": "none" })))(amount);
}

/** settledOrElse : (outcome : Result Money String, fallback : Money) → Money */
export function settledOrElse(__p0, __p1) {
  const outcome = __ck(__p0, ["result", ["ctors", "tag", [["Money", [["amount", ["int53"]], ["currency", ["string"]]]]]], ["string"]]);
  const fallback = __ck(__p1, ["ctors", "tag", [["Money", [["amount", ["int53"]], ["currency", ["string"]]]]]]);
  return __b_settledOrElse(outcome, fallback);
}

function __b_settledOrElse(outcome, fallback) {
  return ((__s) => ((((__s).tag === "ok") ? ((a) => (a))((__s).value) : fallback)))(outcome);
}

/** settledCurrency : (outcome : Result Money String) → Result String String */
export function settledCurrency(__p0) {
  const outcome = __ck(__p0, ["result", ["ctors", "tag", [["Money", [["amount", ["int53"]], ["currency", ["string"]]]]]], ["string"]]);
  return __b_settledCurrency(outcome);
}

function __b_settledCurrency(outcome) {
  return ((__s) => ((((__s).tag === "ok") ? ((a) => ({ "tag": "ok", "value": __b_currencyOf(a) }))((__s).value) : ((err) => ({ "tag": "error", "error": err }))((__s).error))))(outcome);
}

/** loudRefusal : (outcome : Result Money String) → Result Money String */
export function loudRefusal(__p0) {
  const outcome = __ck(__p0, ["result", ["ctors", "tag", [["Money", [["amount", ["int53"]], ["currency", ["string"]]]]]], ["string"]]);
  return __b_loudRefusal(outcome);
}

function __b_loudRefusal(outcome) {
  return ((__s) => ((((__s).tag === "ok") ? ((a) => ({ "tag": "ok", "value": a }))((__s).value) : ((err) => ({ "tag": "error", "error": __upper(err) }))((__s).error))))(outcome);
}

/** settledMoney : (outcome : Result Money String) → Option Money */
export function settledMoney(__p0) {
  const outcome = __ck(__p0, ["result", ["ctors", "tag", [["Money", [["amount", ["int53"]], ["currency", ["string"]]]]]], ["string"]]);
  return __b_settledMoney(outcome);
}

function __b_settledMoney(outcome) {
  return ((__s) => ((((__s).tag === "ok") ? ((a) => ({ "tag": "some", "value": a }))((__s).value) : { "tag": "none" })))(outcome);
}

/** trackingIds : (states : Array OrderState) → Array String */
export function trackingIds(__p0) {
  const states = __ck(__p0, ["array", ["ctors", "kind", [["draft", []], ["placed", [["orderId", ["int53"]]]], ["shipped", [["orderId", ["int53"]], ["trackingId", ["string"]]]], ["cancelled", [["reason", ["string"]]]]]]]);
  return __b_trackingIds(states);
}

function __b_trackingIds(states) {
  return __map(states, (state) => (((__s) => ((((__s).kind === "shipped") ? ((trackingId) => (trackingId))((__s).trackingId) : "")))(state)));
}

/** refundCount : (amounts : Array Int53) → Int53 */
export function refundCount(__p0) {
  const amounts = __ck(__p0, ["array", ["int53"]]);
  return __b_refundCount(amounts);
}

function __b_refundCount(amounts) {
  return __reduce(amounts, 0, (running, y) => (((y < 0) ? __i53((running + 1)) : running)));
}

/** creditNoteAmount : (amount : Int53) → Int53 */
export function creditNoteAmount(__p0) {
  const amount = __ck(__p0, ["int53"]);
  return __b_creditNoteAmount(amount);
}

function __b_creditNoteAmount(amount) {
  return __i53((-1 * __max(amount, 0)));
}

/** directionLabel : (sign : Int53) → String */
export function directionLabel(__p0) {
  const sign = __ck(__p0, ["int53"]);
  return __b_directionLabel(sign);
}

function __b_directionLabel(sign) {
  return ((__s) => (((__s === -1) ? "credit" : ((__s === 1) ? "debit" : "none"))))(sign);
}

/** categoryName : (category : Category) → String */
export function categoryName(__p0) {
  const category = __ck(__p0, ["mu", "tag", [["leaf", [["name", ["string"]]]], ["group", [["name", ["string"]], ["children", ["array", ["ref", 0]]]]]]]);
  return __b_categoryName(category);
}

function __b_categoryName(category) {
  return ((__s) => ((((__s).tag === "leaf") ? ((name) => (name))((__s).name) : ((name) => (name))((__s).name))))(category);
}

/** directChildren : (category : Category) → Int53 */
export function directChildren(__p0) {
  const category = __ck(__p0, ["mu", "tag", [["leaf", [["name", ["string"]]]], ["group", [["name", ["string"]], ["children", ["array", ["ref", 0]]]]]]]);
  return __b_directChildren(category);
}

function __b_directChildren(category) {
  return ((__s) => ((((__s).tag === "leaf") ? 0 : ((children) => (__i53((children).length)))((__s).children))))(category);
}

