// Generated by leants. Do not edit.

const __fail = (code) => {
  const error = new Error(code);
  error.code = code;
  throw error;
};

// Int53 is a mathematical integer, so no -0 survives. In JS both 0 - 0 and -4 % 2 are -0.
const __i53 = (x) => (Number.isSafeInteger(x) ? ((x === 0) ? 0 : x) : __fail("int53Overflow"));

// Math.trunc(a / b) is off by one when a is near 2^53. Integer division avoids
// floating-point division.
const __i53div = (a, b) => ((b === 0) ? __fail("divByZero") : Number((BigInt(a) / BigInt(b))));

const __i53mod = (a, b) => ((b === 0) ? __fail("divByZero") : __i53((a % b)));

const __u32mul = (a, b) => (Math.imul(a, b) >>> 0);

const __u32div = (a, b) => ((b === 0) ? __fail("divByZero") : (Math.trunc((a / b)) >>> 0));

const __u32mod = (a, b) => ((b === 0) ? __fail("divByZero") : ((a % b) >>> 0));

const __bigdiv = (a, b) => ((b === 0n) ? __fail("divByZero") : (a / b));

const __bigmod = (a, b) => ((b === 0n) ? __fail("divByZero") : (a % b));

// Math.abs, Math.min and Math.max throw on a BigInt, so the comparisons are written out
// instead.
const __abs = (x) => ((x < 0) ? (-x) : x);

const __min = (a, b) => ((a <= b) ? a : b);

const __max = (a, b) => ((a <= b) ? b : a);

// Array.from splits by code point, where indexing a string splits by UTF-16 unit.
const __chars = (s) => Array.from(s);

const __cp = (c) => (c).codePointAt(0);

const __strlen = (s) => (__chars(s)).length;

const __strcmp = (a, b) => {
  const x = __chars(a);
  const y = __chars(b);
  let i = 0;
  for (const c of x) {
    if ((i >= (y).length)) {
      return 1;
    }
    const d = (__cp(c) - __cp((y)[i]));
    if ((d !== 0)) {
      return ((d < 0) ? -1 : 1);
    }
    i = (i + 1);
  }
  return (((x).length === (y).length) ? 0 : -1);
};

// JS's own trim also strips NBSP, the BOM and the line separators; eval strips only these
// four.
const __ws = (c) => ((c === " ") || ((c === "\t") || ((c === "\n") || (c === "\r"))));

const __lead = (xs) => {
  let n = 0;
  for (const c of xs) {
    if ((!__ws(c))) {
      break;
    }
    n = (n + 1);
  }
  return n;
};

const __trim = (s) => {
  const xs = __chars(s);
  const lo = __lead(xs);
  const hi = ((xs).length - __lead(__areverse(xs)));
  return ((xs).slice(lo, hi)).join("");
};

// toUpperCase is not ASCII: it maps "ß" to "SS", changing the length of the
// string.
const __upper = (s) => {
  let out = "";
  for (const c of __chars(s)) {
    out = (out + (((c >= "a") && (c <= "z")) ? (c).toUpperCase() : c));
  }
  return out;
};

const __lower = (s) => {
  let out = "";
  for (const c of __chars(s)) {
    out = (out + (((c >= "A") && (c <= "Z")) ? (c).toLowerCase() : c));
  }
  return out;
};

// Native, unlike the four above: UTF-16 preserves prefixes and suffixes and no argument can
// hold a lone surrogate, so a match on units is a match on code points.
const __startsWith = (s, t) => (s).startsWith(t);

const __endsWith = (s, t) => (s).endsWith(t);

const __includes = (s, t) => (s).includes(t);

// split("") returns the UTF-16 units, where eval returns the whole string.
const __split = (s, sep) => ((sep === "") ? [s] : (s).split(sep));

// Indices count code points, and one outside the string fails rather than being clamped.
const __substring = (s, lo, hi) => {
  const xs = __chars(s);
  return ((Number.isSafeInteger(lo) && (Number.isSafeInteger(hi) && ((lo >= 0) && ((hi >= lo) && (hi <= (xs).length))))) ? ((xs).slice(lo, hi)).join("") : __fail("indexOutOfBounds"));
};

// Bounds outside the array fail rather than being clamped, the way an index read does.
const __aslice = (xs, lo, hi) => ((Number.isSafeInteger(lo) && (Number.isSafeInteger(hi) && ((lo >= 0) && ((hi >= lo) && (hi <= (xs).length))))) ? (xs).slice(lo, hi) : __fail("indexOutOfBounds"));

const __aconcat = (a, b) => {
  const out = [];
  for (const v of a) {
    out.push(v);
  }
  for (const v of b) {
    out.push(v);
  }
  return out;
};

// A fresh array: reverse() would otherwise write through to the caller's.
const __areverse = (xs) => {
  const out = [];
  let i = (xs).length;
  for (const v of xs) {
    i = (i - 1);
    out.push((xs)[i]);
  }
  return out;
};

// An out-of-range index fails rather than yielding undefined. undefined does not exist in
// the subset.
const __at = (xs, i) => ((Number.isSafeInteger(i) && ((i >= 0) && (i < (xs).length))) ? (xs)[i] : __fail("indexOutOfBounds"));

const __dget = (d, k) => ((d).has(k) ? { tag: "some", value: (d).get(k) } : { tag: "none" });

const __dhas = (d, k) => (d).has(k);

// A fresh Map: values in the subset are immutable, so set cannot write through to the
// caller's.
const __dset = (d, k, v) => {
  const out = new Map(d);
  out.set(k, v);
  return out;
};

const __dkeys = (d) => Array.from((d).keys());

const __dvalues = (d) => Array.from((d).values());

const __ddelete = (d, k) => {
  const out = new Map();
  for (const key of __dkeys(d)) {
    if ((key !== k)) {
      out.set(key, (d).get(key));
    }
  }
  return out;
};

// === compares references, so it is unusable on constructor values and arrays.
const __eq = (a, b) => {
  if ((a === b)) {
    return true;
  }
  if (((typeof a) !== (typeof b))) {
    return false;
  }
  if (((typeof a) !== "object")) {
    return false;
  }
  if (((a === null) || (b === null))) {
    return false;
  }
  if (((a instanceof Map) || (b instanceof Map))) {
    if ((!((a instanceof Map) && (b instanceof Map)))) {
      return false;
    }
    if (((a).size !== (b).size)) {
      return false;
    }
    const ks = __dkeys(a);
    const ls = __dkeys(b);
    let i = 0;
    for (const key of ks) {
      if (((ls)[i] !== key)) {
        return false;
      }
      if ((!__eq((a).get(key), (b).get(key)))) {
        return false;
      }
      i = (i + 1);
    }
    return true;
  }
  if ((Array.isArray(a) || Array.isArray(b))) {
    if ((!(Array.isArray(a) && Array.isArray(b)))) {
      return false;
    }
    if (((a).length !== (b).length)) {
      return false;
    }
    let i = 0;
    for (const v of a) {
      if ((!__eq(v, (b)[i]))) {
        return false;
      }
      i = (i + 1);
    }
    return true;
  }
  const keys = Object.keys(a);
  if (((keys).length !== (Object.keys(b)).length)) {
    return false;
  }
  for (const key of keys) {
    if ((!Object.hasOwn(b, key))) {
      return false;
    }
    if ((!__eq((a)[key], (b)[key]))) {
      return false;
    }
  }
  return true;
};

const __map = (xs, f) => {
  const out = [];
  for (const v of xs) {
    out.push((f)(v));
  }
  return out;
};

const __filter = (xs, f) => {
  const out = [];
  for (const v of xs) {
    if ((f)(v)) {
      out.push(v);
    }
  }
  return out;
};

// Stops at the first element the predicate accepts, so a predicate that would trap later
// never runs.
const __find = (xs, f) => {
  for (const v of xs) {
    if ((f)(v)) {
      return { tag: "some", value: v };
    }
  }
  return { tag: "none" };
};

const __all = (xs, f) => {
  for (const v of xs) {
    if ((!(f)(v))) {
      return false;
    }
  }
  return true;
};

const __any = (xs, f) => {
  for (const v of xs) {
    if ((f)(v)) {
      return true;
    }
  }
  return false;
};

const __reduce = (xs, init, f) => {
  let acc = init;
  for (const v of xs) {
    acc = (f)(acc, v);
  }
  return acc;
};

const __isObj = (x) => (((typeof x) === "object") && ((x !== null) && (!Array.isArray(x))));

// A key the declared type does not name is ignored rather than refused: TypeScript lets a
// value reach a call carrying extra properties, and __ck drops them before the body runs.
const __hasFields = (x, fields) => {
  for (const f of fields) {
    if ((!Object.hasOwn(x, (f)[0]))) {
      return false;
    }
    if ((!__has((x)[(f)[0]], (f)[1]))) {
      return false;
    }
  }
  return true;
};

const __has = (x, t) => {
  const k = (t)[0];
  if ((k === "bool")) {
    return ((typeof x) === "boolean");
  }
  if ((k === "int53")) {
    return (((typeof x) === "number") && Number.isSafeInteger(x));
  }
  if ((k === "uint32")) {
    return (((typeof x) === "number") && (Number.isInteger(x) && ((x >= 0) && (x <= 4294967295))));
  }
  if ((k === "string")) {
    return ((typeof x) === "string");
  }
  if ((k === "bigint")) {
    return ((typeof x) === "bigint");
  }
  if ((k === "array")) {
    return (Array.isArray(x) && __all(x, ((e) => __has(e, (t)[1]))));
  }
  if ((k === "dict")) {
    if ((!(x instanceof Map))) {
      return false;
    }
    if ((!__all(__dkeys(x), ((key) => ((typeof key) === "string"))))) {
      return false;
    }
    return __all(__dvalues(x), ((e) => __has(e, (t)[1])));
  }
  if ((!__isObj(x))) {
    return false;
  }
  if ((k === "option")) {
    if (((x).tag === "none")) {
      return __hasFields(x, []);
    }
    return (((x).tag === "some") && __hasFields(x, [["value", (t)[1]]]));
  }
  if ((k === "result")) {
    if (((x).tag === "ok")) {
      return __hasFields(x, [["value", (t)[1]]]);
    }
    return (((x).tag === "error") && __hasFields(x, [["error", (t)[2]]]));
  }
  const alt = __find((t)[1], ((c) => ((c)[0] === (x).tag)));
  return (((alt).tag === "some") && __hasFields(x, ((alt).value)[1]));
};

const __normFields = (x, fields) => {
  const out = [["tag", (x).tag]];
  for (const f of fields) {
    if (Object.hasOwn(x, (f)[0])) {
      out.push([(f)[0], __norm((x)[(f)[0]], (f)[1])]);
    }
  }
  return Object.fromEntries(out);
};

const __norm = (x, t) => {
  const k = (t)[0];
  if ((k === "array")) {
    const out = [];
    for (const e of x) {
      out.push(__norm(e, (t)[1]));
    }
    return out;
  }
  if ((k === "dict")) {
    const out = new Map();
    for (const key of __dkeys(x)) {
      out.set(key, __norm((x).get(key), (t)[1]));
    }
    return out;
  }
  if ((k === "option")) {
    if (((x).tag === "none")) {
      return __normFields(x, []);
    }
    if (((x).tag === "some")) {
      return __normFields(x, [["value", (t)[1]]]);
    }
    return x;
  }
  if ((k === "result")) {
    if (((x).tag === "ok")) {
      return __normFields(x, [["value", (t)[1]]]);
    }
    if (((x).tag === "error")) {
      return __normFields(x, [["error", (t)[2]]]);
    }
    return x;
  }
  if ((k === "ctors")) {
    const alt = __find((t)[1], ((c) => ((c)[0] === (x).tag)));
    if (((alt).tag === "some")) {
      return __normFields(x, ((alt).value)[1]);
    }
    return x;
  }
  return x;
};

// Numbers are handed back as they came, unlike __i53: a -0 argument is a safe integer, and
// every answer built from it passes through __i53 or a comparison that already treats -0
// and 0 alike, so normalising one here would change nothing a caller can observe.
const __ck = (x, t) => (__has(x, t) ? __norm(x, t) : __fail("typeError"));

/** add : (a : Int53, b : Int53) → Int53 */
export function add(__p0, __p1) {
  const a = __ck(__p0, ["int53"]);
  const b = __ck(__p1, ["int53"]);
  return __i53((a + b));
}

/** clampQuantity : (quantity : Int53, upper : Int53) → Int53 */
export function clampQuantity(__p0, __p1) {
  const quantity = __ck(__p0, ["int53"]);
  const upper = __ck(__p1, ["int53"]);
  return ((quantity < 1) ? 1 : ((quantity > upper) ? upper : quantity));
}

/** lineTotal : (unitPrice : Int53, quantity : Int53) → Int53 */
export function lineTotal(__p0, __p1) {
  const unitPrice = __ck(__p0, ["int53"]);
  const quantity = __ck(__p1, ["int53"]);
  return __i53((unitPrice * clampQuantity(quantity, 999)));
}

/** discounted : (amount : Int53, percent : Int53) → Int53 */
export function discounted(__p0, __p1) {
  const amount = __ck(__p0, ["int53"]);
  const percent = __ck(__p1, ["int53"]);
  const rate = __i53((100 - ((percent < 0) ? 0 : ((percent > 100) ? 100 : percent))));
  return __i53div(__i53((amount * rate)), 100);
}

/** divide : (a : Int53, b : Int53) → Int53 */
export function divide(__p0, __p1) {
  const a = __ck(__p0, ["int53"]);
  const b = __ck(__p1, ["int53"]);
  return __i53div(a, b);
}

/** remainder : (a : Int53, b : Int53) → Int53 */
export function remainder(__p0, __p1) {
  const a = __ck(__p0, ["int53"]);
  const b = __ck(__p1, ["int53"]);
  return __i53mod(a, b);
}

/** negate : (a : Int53) → Int53 */
export function negate(__p0) {
  const a = __ck(__p0, ["int53"]);
  return __i53((-a));
}

/** priceGap : (a : Int53, b : Int53) → Int53 */
export function priceGap(__p0, __p1) {
  const a = __ck(__p0, ["int53"]);
  const b = __ck(__p1, ["int53"]);
  return __i53(__abs(__i53((a - b))));
}

/** cappedCharge : (amount : Int53, budget : Int53) → Int53 */
export function cappedCharge(__p0, __p1) {
  const amount = __ck(__p0, ["int53"]);
  const budget = __ck(__p1, ["int53"]);
  return __min(amount, budget);
}

/** atLeast : (amount : Int53, floor : Int53) → Int53 */
export function atLeast(__p0, __p1) {
  const amount = __ck(__p0, ["int53"]);
  const floor = __ck(__p1, ["int53"]);
  return __max(amount, floor);
}

/** noDiscount : (amount : Int53) → Int53 */
export function noDiscount(__p0) {
  const amount = __ck(__p0, ["int53"]);
  return amount;
}

/** tenPercentOff : (amount : Int53) → Int53 */
export function tenPercentOff(__p0) {
  const amount = __ck(__p0, ["int53"]);
  return __i53((amount - __i53div(amount, 10)));
}

/** priced : (rule : (Int53) => Int53, amount : Int53) → Int53 */
function priced(__p0, __p1) {
  const rule = __p0;
  const amount = __ck(__p1, ["int53"]);
  return rule(amount);
}

/** memberPrice : (amount : Int53) → Int53 */
export function memberPrice(__p0) {
  const amount = __ck(__p0, ["int53"]);
  return priced(tenPercentOff, amount);
}

/** guestPrice : (amount : Int53) → Int53 */
export function guestPrice(__p0) {
  const amount = __ck(__p0, ["int53"]);
  return priced(noDiscount, amount);
}

/** safeQuotientIsPositive : (a : Int53, b : Int53) → Bool */
export function safeQuotientIsPositive(__p0, __p1) {
  const a = __ck(__p0, ["int53"]);
  const b = __ck(__p1, ["int53"]);
  return ((b !== 0) && (__i53div(a, b) > 0));
}

/** canCheckout : (signedIn : Bool, cartTotal : Int53, stock : Int53) → Bool */
export function canCheckout(__p0, __p1, __p2) {
  const signedIn = __ck(__p0, ["bool"]);
  const cartTotal = __ck(__p1, ["int53"]);
  const stock = __ck(__p2, ["int53"]);
  return ((signedIn && (cartTotal > 0)) && (stock >= 1));
}

/** mixChannels : (a : UInt32, b : UInt32) → UInt32 */
export function mixChannels(__p0, __p1) {
  const a = __ck(__p0, ["uint32"]);
  const b = __ck(__p1, ["uint32"]);
  return ((__u32mul(a, b) + ((a - b) >>> 0)) >>> 0);
}

/** bucketOf : (key : UInt32, buckets : UInt32) → UInt32 */
export function bucketOf(__p0, __p1) {
  const key = __ck(__p0, ["uint32"]);
  const buckets = __ck(__p1, ["uint32"]);
  return __u32mod(key, buckets);
}

/** scaleFee : (fee : BigInt, factor : BigInt) → BigInt */
export function scaleFee(__p0, __p1) {
  const fee = __ck(__p0, ["bigint"]);
  const factor = __ck(__p1, ["bigint"]);
  return ((fee * factor) - 1n);
}

/** bigQuotient : (a : BigInt, b : BigInt) → BigInt */
export function bigQuotient(__p0, __p1) {
  const a = __ck(__p0, ["bigint"]);
  const b = __ck(__p1, ["bigint"]);
  return __bigdiv(a, b);
}

/** slugOf : (prefix : String, name : String) → String */
export function slugOf(__p0, __p1) {
  const prefix = __ck(__p0, ["string"]);
  const name = __ck(__p1, ["string"]);
  return ((prefix + "-") + name);
}

/** sortsBefore : (a : String, b : String) → Bool */
export function sortsBefore(__p0, __p1) {
  const a = __ck(__p0, ["string"]);
  const b = __ck(__p1, ["string"]);
  return (__strcmp(a, b) < 0);
}

/** sameLabel : (a : String, b : String) → Bool */
export function sameLabel(__p0, __p1) {
  const a = __ck(__p0, ["string"]);
  const b = __ck(__p1, ["string"]);
  return (a === b);
}

/** rebindTwice : (amount : Int53) → Int53 */
export function rebindTwice(__p0) {
  const amount = __ck(__p0, ["int53"]);
  return ((amount) => (((amount) => (amount))(__i53((amount * 2)))))(__i53((amount + 1)));
}

/** roleRank : (role : Role) → Int53 */
export function roleRank(__p0) {
  const role = __ck(__p0, ["ctors", [["guest", []], ["member", []], ["admin", []]]]);
  return ((__s) => ((((__s).tag === "guest") ? 0 : (((__s).tag === "member") ? 1 : 2))))(role);
}

/** addMoney : (a : Money, b : Money) → Result Money String */
export function addMoney(__p0, __p1) {
  const a = __ck(__p0, ["ctors", [["Money", [["amount", ["int53"]], ["currency", ["string"]]]]]]);
  const b = __ck(__p1, ["ctors", [["Money", [["amount", ["int53"]], ["currency", ["string"]]]]]]);
  return (((a).currency !== (b).currency) ? { "tag": "error", "error": "currency mismatch" } : { "tag": "ok", "value": { "tag": "Money", "amount": __i53(((a).amount + (b).amount)), "currency": (a).currency } });
}

/** sameMoney : (a : Money, b : Money) → Bool */
export function sameMoney(__p0, __p1) {
  const a = __ck(__p0, ["ctors", [["Money", [["amount", ["int53"]], ["currency", ["string"]]]]]]);
  const b = __ck(__p1, ["ctors", [["Money", [["amount", ["int53"]], ["currency", ["string"]]]]]]);
  return __eq(a, b);
}

/** ship : (state : OrderState, trackingId : String) → Result OrderState String */
export function ship(__p0, __p1) {
  const state = __ck(__p0, ["ctors", [["draft", []], ["placed", [["orderId", ["int53"]]]], ["shipped", [["orderId", ["int53"]], ["trackingId", ["string"]]]], ["cancelled", [["reason", ["string"]]]]]]);
  const trackingId = __ck(__p1, ["string"]);
  return ((__s) => ((((__s).tag === "draft") ? { "tag": "error", "error": "a draft order cannot ship" } : (((__s).tag === "placed") ? ((orderId) => (((trackingId === "") ? { "tag": "error", "error": "a tracking id is required" } : { "tag": "ok", "value": { "tag": "shipped", "orderId": orderId, "trackingId": trackingId } })))((__s).orderId) : (((__s).tag === "shipped") ? ((orderId, trackingId) => ({ "tag": "error", "error": "the order has already shipped" }))((__s).orderId, (__s).trackingId) : ((reason) => ({ "tag": "error", "error": "a cancelled order cannot ship" }))((__s).reason))))))(state);
}

/** trackingOf : (state : OrderState) → Option String */
export function trackingOf(__p0) {
  const state = __ck(__p0, ["ctors", [["draft", []], ["placed", [["orderId", ["int53"]]]], ["shipped", [["orderId", ["int53"]], ["trackingId", ["string"]]]], ["cancelled", [["reason", ["string"]]]]]]);
  return ((__s) => ((((__s).tag === "draft") ? { "tag": "none" } : (((__s).tag === "placed") ? ((orderId) => ({ "tag": "none" }))((__s).orderId) : (((__s).tag === "shipped") ? ((orderId, trackingId) => ({ "tag": "some", "value": trackingId }))((__s).orderId, (__s).trackingId) : ((reason) => ({ "tag": "none" }))((__s).reason))))))(state);
}

/** canRefund : (role : Role, state : OrderState) → Bool */
export function canRefund(__p0, __p1) {
  const role = __ck(__p0, ["ctors", [["guest", []], ["member", []], ["admin", []]]]);
  const state = __ck(__p1, ["ctors", [["draft", []], ["placed", [["orderId", ["int53"]]]], ["shipped", [["orderId", ["int53"]], ["trackingId", ["string"]]]], ["cancelled", [["reason", ["string"]]]]]]);
  return ((__s) => ((((__s).tag === "draft") ? false : (((__s).tag === "placed") ? ((orderId) => ((roleRank(role) >= 1)))((__s).orderId) : (((__s).tag === "shipped") ? ((orderId, trackingId) => ((roleRank(role) >= 2)))((__s).orderId, (__s).trackingId) : ((reason) => (false))((__s).reason))))))(state);
}

/** total : (xs : Array Int53) → Int53 */
export function total(__p0) {
  const xs = __ck(__p0, ["array", ["int53"]]);
  return __reduce(xs, 0, (sum, x) => (__i53((sum + x))));
}

/** headOr : (xs : Array Int53, fallback : Int53) → Int53 */
export function headOr(__p0, __p1) {
  const xs = __ck(__p0, ["array", ["int53"]]);
  const fallback = __ck(__p1, ["int53"]);
  return ((__i53((xs).length) === 0) ? fallback : __at(xs, 0));
}

/** firstTracking : (states : Array OrderState) → Option String */
export function firstTracking(__p0) {
  const states = __ck(__p0, ["array", ["ctors", [["draft", []], ["placed", [["orderId", ["int53"]]]], ["shipped", [["orderId", ["int53"]], ["trackingId", ["string"]]]], ["cancelled", [["reason", ["string"]]]]]]]);
  return ((__i53((states).length) === 0) ? { "tag": "none" } : trackingOf(__at(states, 0)));
}

/** pageOf : (xs : Array Int53, lo : Int53, hi : Int53) → Array Int53 */
export function pageOf(__p0, __p1, __p2) {
  const xs = __ck(__p0, ["array", ["int53"]]);
  const lo = __ck(__p1, ["int53"]);
  const hi = __ck(__p2, ["int53"]);
  return __aslice(xs, lo, hi);
}

/** mostRecentFirst : (events : Array String) → Array String */
export function mostRecentFirst(__p0) {
  const events = __ck(__p0, ["array", ["string"]]);
  return __areverse(events);
}

/** combinedCart : (saved : Array Int53, added : Array Int53) → Array Int53 */
export function combinedCart(__p0, __p1) {
  const saved = __ck(__p0, ["array", ["int53"]]);
  const added = __ck(__p1, ["array", ["int53"]]);
  return __aconcat(saved, added);
}

/** lineTotals : (unitPrice : Int53, quantities : Array Int53) → Array Int53 */
export function lineTotals(__p0, __p1) {
  const unitPrice = __ck(__p0, ["int53"]);
  const quantities = __ck(__p1, ["array", ["int53"]]);
  return __map(quantities, (quantity) => (lineTotal(unitPrice, quantity)));
}

/** currenciesOf : (items : Array Money) → Array String */
export function currenciesOf(__p0) {
  const items = __ck(__p0, ["array", ["ctors", [["Money", [["amount", ["int53"]], ["currency", ["string"]]]]]]]);
  return __map(items, (item) => ((item).currency));
}

/** refundableOnly : (role : Role, states : Array OrderState) → Array OrderState */
export function refundableOnly(__p0, __p1) {
  const role = __ck(__p0, ["ctors", [["guest", []], ["member", []], ["admin", []]]]);
  const states = __ck(__p1, ["array", ["ctors", [["draft", []], ["placed", [["orderId", ["int53"]]]], ["shipped", [["orderId", ["int53"]], ["trackingId", ["string"]]]], ["cancelled", [["reason", ["string"]]]]]]]);
  return __filter(states, (state) => (canRefund(role, state)));
}

/** cartTotal : (items : Array Money) → Int53 */
export function cartTotal(__p0) {
  const items = __ck(__p0, ["array", ["ctors", [["Money", [["amount", ["int53"]], ["currency", ["string"]]]]]]]);
  return __reduce(items, 0, (subtotal, item) => (__i53((subtotal + (item).amount))));
}

/** anyOverLimit : (amounts : Array Int53, limit : Int53) → Bool */
export function anyOverLimit(__p0, __p1) {
  const amounts = __ck(__p0, ["array", ["int53"]]);
  const limit = __ck(__p1, ["int53"]);
  return __reduce(amounts, false, (seen, amount) => ((seen ? true : (amount > limit))));
}

/** firstOverLimit : (amounts : Array Int53, limit : Int53) → Option Int53 */
export function firstOverLimit(__p0, __p1) {
  const amounts = __ck(__p0, ["array", ["int53"]]);
  const limit = __ck(__p1, ["int53"]);
  return __find(amounts, (amount) => ((amount > limit)));
}

/** everyLineWithinLimit : (amounts : Array Int53, limit : Int53) → Bool */
export function everyLineWithinLimit(__p0, __p1) {
  const amounts = __ck(__p0, ["array", ["int53"]]);
  const limit = __ck(__p1, ["int53"]);
  return __all(amounts, (amount) => ((amount <= limit)));
}

/** someLineIsFree : (amounts : Array Int53) → Bool */
export function someLineIsFree(__p0) {
  const amounts = __ck(__p0, ["array", ["int53"]]);
  return __any(amounts, (amount) => ((amount === 0)));
}

/** quantityLabel : (quantity : Int53) → String */
export function quantityLabel(__p0) {
  const quantity = __ck(__p0, ["int53"]);
  return ((__s) => (((__s === 0) ? "out of stock" : ((__s === 1) ? "last one" : "in stock"))))(quantity);
}

/** renewalLabel : (autoRenew : Bool) → String */
export function renewalLabel(__p0) {
  const autoRenew = __ck(__p0, ["bool"]);
  return ((__s) => (((__s === true) ? "renews" : "ends")))(autoRenew);
}

/** chargeable : (amount : Money) → Bool */
export function chargeable(__p0) {
  const amount = __ck(__p0, ["ctors", [["Money", [["amount", ["int53"]], ["currency", ["string"]]]]]]);
  return ((__s) => (((((__s).tag === "Money") && ((__s).amount === 0)) ? false : ((((__s).tag === "Money") && ((__s).currency === "")) ? false : ((value) => ((value > 0)))((__s).amount)))))(amount);
}

/** settleMessage : (outcome : Result OrderState String) → String */
export function settleMessage(__p0) {
  const outcome = __ck(__p0, ["result", ["ctors", [["draft", []], ["placed", [["orderId", ["int53"]]]], ["shipped", [["orderId", ["int53"]], ["trackingId", ["string"]]]], ["cancelled", [["reason", ["string"]]]]]], ["string"]]);
  return ((__s) => (((((__s).tag === "ok") && (((__s).value).tag === "shipped")) ? ((trackingId) => (trackingId))(((__s).value).trackingId) : ((((__s).tag === "ok") && (((__s).value).tag === "placed")) ? "awaiting shipment" : (((__s).tag === "ok") ? "no update" : ((message) => (message))((__s).error))))))(outcome);
}

/** remainingItems : (page : Paginated Money) → Int53 */
export function remainingItems(__p0) {
  const page = __ck(__p0, ["ctors", [["Paginated", [["items", ["array", ["ctors", [["Money", [["amount", ["int53"]], ["currency", ["string"]]]]]]]], ["total", ["int53"]]]]]]);
  return __i53(((page).total - __i53(((page).items).length)));
}

/** firstPage : (amounts : Array Int53) → Paginated Int53 */
export function firstPage(__p0) {
  const amounts = __ck(__p0, ["array", ["int53"]]);
  return { "tag": "Paginated", "items": amounts, "total": __i53((amounts).length) };
}

/** validateQuantity : (quantity : Int53) → Validated String Int53 */
export function validateQuantity(__p0) {
  const quantity = __ck(__p0, ["int53"]);
  return ((quantity < 1) ? { "tag": "invalid", "errors": ["a quantity must be at least 1"] } : ((quantity > 999) ? { "tag": "invalid", "errors": ["a quantity may not exceed 999"] } : { "tag": "valid", "value": quantity }));
}

/** validationMessage : (outcome : Validated String Int53) → String */
export function validationMessage(__p0) {
  const outcome = __ck(__p0, ["ctors", [["valid", [["value", ["int53"]]]], ["invalid", [["errors", ["array", ["string"]]]]]]]);
  return ((__s) => ((((__s).tag === "valid") ? ((value) => (quantityLabel(value)))((__s).value) : ((errors) => (((__i53((errors).length) === 0) ? "refused" : __at(errors, 0))))((__s).errors))))(outcome);
}

/** storedCoupon : (campaign : String, entered : String) → String */
export function storedCoupon(__p0, __p1) {
  const campaign = __ck(__p0, ["string"]);
  const entered = __ck(__p1, ["string"]);
  return __upper(__trim((campaign + entered)));
}

/** couponApplies : (code : String, campaign : String) → Bool */
export function couponApplies(__p0, __p1) {
  const code = __ck(__p0, ["string"]);
  const campaign = __ck(__p1, ["string"]);
  return __startsWith(__lower(__trim(code)), __lower(__trim(campaign)));
}

/** mentionsTerm : (text : String, term : String) → Bool */
export function mentionsTerm(__p0, __p1) {
  const text = __ck(__p0, ["string"]);
  const term = __ck(__p1, ["string"]);
  return __includes(__lower(text), __lower(term));
}

/** fieldCount : (row : String, separator : String) → Int53 */
export function fieldCount(__p0, __p1) {
  const row = __ck(__p0, ["string"]);
  const separator = __ck(__p1, ["string"]);
  return __i53((__split(row, separator)).length);
}

/** truncateLabel : (label : String, limit : Int53) → String */
export function truncateLabel(__p0, __p1) {
  const label = __ck(__p0, ["string"]);
  const limit = __ck(__p1, ["int53"]);
  return ((__i53(__strlen(label)) <= limit) ? label : (__substring(label, 0, limit) + "..."));
}

/** isSpreadsheet : (fileName : String) → Bool */
export function isSpreadsheet(__p0) {
  const fileName = __ck(__p0, ["string"]);
  return __endsWith(__lower(__trim(fileName)), ".csv");
}

/** limitsFor : (role : Role) → Dict Int53 */
export function limitsFor(__p0) {
  const role = __ck(__p0, ["ctors", [["guest", []], ["member", []], ["admin", []]]]);
  return ((__s) => ((((__s).tag === "guest") ? new Map([["daily", 10], ["monthly", 100]]) : (((__s).tag === "member") ? new Map([["daily", 100], ["monthly", 3000]]) : new Map([["daily", 1000], ["monthly", 30000]])))))(role);
}

/** dailyLimit : (role : Role) → Int53 */
export function dailyLimit(__p0) {
  const role = __ck(__p0, ["ctors", [["guest", []], ["member", []], ["admin", []]]]);
  return ((__s) => ((((__s).tag === "some") ? ((value) => (value))((__s).value) : 0)))(__dget(limitsFor(role), "daily"));
}

/** priceOf : (prices : Dict Int53, sku : String) → Option Int53 */
export function priceOf(__p0, __p1) {
  const prices = __ck(__p0, ["dict", ["int53"]]);
  const sku = __ck(__p1, ["string"]);
  return __dget(prices, sku);
}

/** isListed : (prices : Dict Int53, sku : String) → Bool */
export function isListed(__p0, __p1) {
  const prices = __ck(__p0, ["dict", ["int53"]]);
  const sku = __ck(__p1, ["string"]);
  return __dhas(prices, sku);
}

/** repriced : (prices : Dict Int53, sku : String, amount : Int53) → Dict Int53 */
export function repriced(__p0, __p1, __p2) {
  const prices = __ck(__p0, ["dict", ["int53"]]);
  const sku = __ck(__p1, ["string"]);
  const amount = __ck(__p2, ["int53"]);
  return __dset(prices, sku, amount);
}

/** listedSkus : (prices : Dict Int53) → Array String */
export function listedSkus(__p0) {
  const prices = __ck(__p0, ["dict", ["int53"]]);
  return __dkeys(prices);
}

/** listedPrices : (prices : Dict Int53) → Array Int53 */
export function listedPrices(__p0) {
  const prices = __ck(__p0, ["dict", ["int53"]]);
  return __dvalues(prices);
}

/** withdrawn : (prices : Dict Int53, sku : String) → Dict Int53 */
export function withdrawn(__p0, __p1) {
  const prices = __ck(__p0, ["dict", ["int53"]]);
  const sku = __ck(__p1, ["string"]);
  return __ddelete(prices, sku);
}

/** catalogueSize : (prices : Dict Int53) → Int53 */
export function catalogueSize(__p0) {
  const prices = __ck(__p0, ["dict", ["int53"]]);
  return __i53((prices).size);
}

//# sourceMappingURL=index.js.map
