// Generated by leants. Do not edit.

export declare function add(a: number, b: number): number;

export declare function clampQuantity(quantity: number, upper: number): number;

export declare function lineTotal(unitPrice: number, quantity: number): number;

export declare function discounted(amount: number, percent: number): number;

export declare function divide(a: number, b: number): number;

export declare function remainder(a: number, b: number): number;

export declare function negate(a: number): number;

export declare function safeQuotientIsPositive(a: number, b: number): boolean;

export declare function canCheckout(signedIn: boolean, cartTotal: number, stock: number): boolean;

export declare function mixChannels(a: number, b: number): number;

export declare function bucketOf(key: number, buckets: number): number;

export declare function scaleFee(fee: bigint, factor: bigint): bigint;

export declare function bigQuotient(a: bigint, b: bigint): bigint;

export declare function slugOf(prefix: string, name: string): string;

export declare function sortsBefore(a: string, b: string): boolean;

export declare function sameLabel(a: string, b: string): boolean;

export declare function rebindTwice(amount: number): number;
