import Lean2Js.Json
import Lean2Js.Core

/-!
# Manifest

The proof manifest that accompanies the artifact.

What a user writes is only what a user knows: the package's name, its version and how it may be published.
Everything else the manifest says is a fact about the build — the compiler's version, Lean's, the module
the package was read out of, the theorems proved there and the axioms their proofs reach — and a manifest
that let any of them be typed in by hand could be made to say something the build does not. A theorem's
statement is one of those facts: a sentence written beside a proof can drift from what the proof proves.
-/

namespace Lean2Js

/-- A theorem the package is sold on, as `lean2js` read it out of the build: the signature Lean prints for
it, and the docstring written above it. -/
structure Claim where
  name : String
  statement : String
  doc : Option String

structure Manifest where
  package : String
  version : String
  isPrivate : Bool := true
  license : Option String := none
  repository : Option String := none

/-- What a package is emitted from. Only `manifest` is written by hand; `lean2js` reads the program and the
public theorems out of the manifest's namespace. -/
structure Artifact where
  manifest : Manifest
  program : Core.Program
  claims : List Claim
  source : String
  axioms : List String

/-- Kept alongside the lakefile's `version`; `scripts/check-template.sh` fails when the two drift. -/
def compilerVersion : String := "0.1.0"

/-- The transcribed source ships under the package's own name rather than a fixed one, so that a stack
trace through the source map names the package the frame came from. -/
def Manifest.sourceFileName (m : Manifest) : String :=
  ((m.package.splitOn "/").getLastD m.package) ++ ".lean2js"

def Artifact.toJson (a : Artifact) : Json :=
  let exports := a.program.publicDecls.map fun d =>
    let params := d.params.map fun p => s!"{p.name} : {p.ty.render}"
    Json.obj [
      ("name", .str d.name),
      ("signature", .str s!"({String.intercalate ", " params}) → {d.ret.render}")
    ]
  let claims := a.claims.map fun c =>
    Json.obj ([("name", .str c.name), ("statement", .str c.statement)] ++
      c.doc.toList.map fun doc => ("doc", .str doc))
  .obj [
    ("package", .str a.manifest.package),
    ("version", .str a.manifest.version),
    ("compiler", .obj [("name", .str "lean2js"), ("version", .str compilerVersion)]),
    ("lean", .obj [("version", .str Lean.versionString), ("githash", .str Lean.githash)]),
    ("source", .str a.source),
    ("exports", .arr exports),
    ("theorems", .arr claims),
    ("axioms", .arr (a.axioms.map .str))
  ]

def Artifact.toReadme (a : Artifact) : String :=
  let exports := a.program.publicDecls.map fun d =>
    let params := String.intercalate ", " (d.params.map fun p => s!"{p.name} : {p.ty.render}")
    s!"- `{d.name}({params}) → {d.ret.render}`"
  let claims := a.claims.flatMap fun c =>
    [s!"### {c.name}", ""] ++ c.doc.toList.flatMap (fun doc => [doc, ""]) ++
      ["```lean", s!"theorem {c.statement}", "```", ""]
  let axioms :=
    if a.axioms.isEmpty then "The proofs above reach no axioms."
    else s!"The proofs above reach no axioms beyond {String.intercalate ", " a.axioms}."
  String.intercalate "\n" (
    [ s!"# {a.manifest.package}",
      "",
      s!"Generated by lean2js {compilerVersion} from `{a.source}` with Lean {Lean.versionString}.",
      "",
      "## Exports",
      "" ] ++ exports ++
    [ "",
      "## Theorems",
      "",
      "Proved in Lean about the reference semantics the generated JavaScript is checked against. Each \
        statement is the one Lean prints for the theorem, and `proof-manifest.json` lists the same ones.",
      "" ] ++ claims ++
    [ "## Axioms",
      "",
      axioms,
      "" ])

end Lean2Js
