import Lean2Js.Render
import Lean2Js.Js

/-!
# The source map from the generated `index.js` to the `.lean2js` source

The source map from the generated `index.js` to the `.lean2js` source.

Mappings are per function. They do not reach inside expressions because Core terms carry no position
information. A stack trace still tells you which declaration of which function it lands in.
-/

namespace Lean2Js

private def base64 : String :=
  "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"

private def base64Char (n : Nat) : String :=
  String.singleton (base64.toList.getD n 'A')

/-- The source map's variable-length number. The sign goes in the lowest bit, then five bits at a time
from the bottom. -/
partial def vlq (value : Int) : String :=
  let unsigned := if value < 0 then ((-value).toNat * 2) + 1 else value.toNat * 2
  let rec go (n : Nat) (acc : String) : String :=
    let digit := n % 32
    let rest := n / 32
    if rest == 0 then acc ++ base64Char digit
    else go rest (acc ++ base64Char (digit + 32))
  go unsigned ""

structure Mapping where
  generatedLine : Nat
  sourceLine : Nat

/-- Separates each line's group with `;`. The column resets to 0 every line, and the source line is
written as a delta from the previous one. -/
def encodeMappings (totalLines : Nat) (mappings : List Mapping) : String :=
  let rec go (line : Nat) (prevSource : Int) (acc : List String) : List String :=
    if line ≥ totalLines then acc
    else
      match mappings.find? (·.generatedLine == line) with
      | some m =>
        let source := Int.ofNat m.sourceLine
        go (line + 1) source (acc ++ [vlq 0 ++ vlq 0 ++ vlq (source - prevSource) ++ vlq 0])
      | none => go (line + 1) prevSource (acc ++ [""])
  String.intercalate ";" (go 0 0 [])

def sourceMapJson (sourceName : String) (source : Core.Source)
    (totalLines : Nat) (mappings : List Mapping) : Json :=
  .obj [
    ("version", .num 3),
    ("file", .str "index.js"),
    ("sources", .arr [.str sourceName]),
    ("sourcesContent", .arr [.str source.text]),
    ("names", .arr []),
    ("mappings", .str (encodeMappings totalLines mappings))
  ]

/-- The text of the generated JS, and which line each function starts on. -/
structure Emitted where
  text : String
  funcLines : List (String × Nat)

private def countLines (s : String) : Nat := (s.splitOn "\n").length

/-- Which line of the body the signature appears on. JSDoc shifts the head, and an internal function has
no `export`, so the lines are counted. -/
private def signatureOffset (f : Js.Func) : Nat :=
  ((f.render.splitOn "\n").findIdx? fun line =>
    line.startsWith "export function " || line.startsWith "function ").getD 0

def emitModule (m : Js.Module) : Emitted :=
  let header := "// Generated by lean2js. Do not edit.\n\n" ++ Js.runtime ++ "\n\n"
  let start := countLines header - 1
  let (_, funcs) := m.funcs.foldl (init := (header, [])) fun (text, funcs) f =>
    let line := start + countLines text - countLines header + signatureOffset f
    (text ++ f.render ++ "\n\n", funcs ++ [(f.name, line)])
  { text := m.render, funcLines := funcs }

def sourceMapFor (p : Core.Program) (emitted : Emitted) (sourceName : String) : Json :=
  let source := p.source
  let mappings := emitted.funcLines.filterMap fun (name, line) =>
    (source.declLines.find? (·.1 == name)).map fun (_, sourceLine) =>
      { generatedLine := line, sourceLine : Mapping }
  sourceMapJson sourceName source (countLines emitted.text) mappings

end Lean2Js
