import LeanTs.Json
import LeanTs.Core

/-!
# Js

出力する JavaScript の AST と ESM / `.d.ts` プリンタ。

括弧は優先順位を見ずに常に付ける。優先順位表はコンパイラの信頼ベースに載る一方、Phase 1 では
何も買わない。読みやすい出力は Phase 3 の課題。
-/

namespace LeanTs.Js

inductive Expr where
  | num (i : Int)
  | bigLit (i : Int)
  | str (s : String)
  | bool (b : Bool)
  | ident (name : String)
  | unary (op : String) (e : Expr)
  | binary (op : String) (lhs rhs : Expr)
  | cond (c t e : Expr)
  | call (callee : String) (args : List Expr)
  | arrowCall (params : List String) (body : Expr) (args : List Expr)
  | objLit (fields : List (String × Expr))
  | member (obj : Expr) (field : String)
  | arrayLit (items : List Expr)
  deriving Inhabited

inductive Stmt where
  | const (name : String) (val : Expr)
  | ret (e : Expr)
  deriving Inhabited

structure Func where
  name : String
  params : List String
  body : List Stmt
  doc : String
  deriving Inhabited

structure Module where
  funcs : List Func
  deriving Inhabited

partial def Expr.render : Expr → String
  | .num i => toString i
  | .bigLit i => toString i ++ "n"
  | .str s => "\"" ++ escapeString s ++ "\""
  | .bool b => if b then "true" else "false"
  | .ident name => name
  | .unary op e => "(" ++ op ++ e.render ++ ")"
  | .binary op lhs rhs => "(" ++ lhs.render ++ " " ++ op ++ " " ++ rhs.render ++ ")"
  | .cond c t e => "(" ++ c.render ++ " ? " ++ t.render ++ " : " ++ e.render ++ ")"
  | .call callee args => callee ++ "(" ++ String.intercalate ", " (args.map Expr.render) ++ ")"
  | .arrowCall params body args =>
    "((" ++ String.intercalate ", " params ++ ") => (" ++ body.render ++ "))("
      ++ String.intercalate ", " (args.map Expr.render) ++ ")"
  | .objLit fields =>
    let field := fun (k, v) => "\"" ++ escapeString k ++ "\": " ++ Expr.render v
    "{ " ++ String.intercalate ", " (fields.map field) ++ " }"
  | .member obj field => "(" ++ obj.render ++ ")." ++ field
  | .arrayLit items => "[" ++ String.intercalate ", " (items.map Expr.render) ++ "]"

def Stmt.render : Stmt → String
  | .const name val => "  const " ++ name ++ " = " ++ val.render ++ ";"
  | .ret e => "  return " ++ e.render ++ ";"

def Func.render (f : Func) : String :=
  let header := if f.doc.isEmpty then "" else "/** " ++ f.doc ++ " */\n"
  header ++ "export function " ++ f.name ++ "(" ++ String.intercalate ", " f.params ++ ") {\n"
    ++ String.intercalate "\n" (f.body.map Stmt.render) ++ "\n}"

/-- 生成コードが呼ぶ実行時ヘルパ。JS と Lean で答えが割れる演算をここに閉じ込めてある。 -/
def runtime : String :=
"const __fail = (code) => {
  const error = new Error(code);
  error.code = code;
  throw error;
};

// Int53 は数学的な整数なので -0 を残さない。JS では 0 - 0 も -4 % 2 も -0 になる。
const __i53 = (x) =>
  Number.isSafeInteger(x) ? (x === 0 ? 0 : x) : __fail(\"int53Overflow\");

// Math.trunc(a / b) は a が 2^53 に近いと 1 ずれる。整数除算に浮動小数の割り算を使わない。
const __i53div = (a, b) =>
  b === 0 ? __fail(\"divByZero\") : Number(BigInt(a) / BigInt(b));

const __i53mod = (a, b) => (b === 0 ? __fail(\"divByZero\") : __i53(a % b));

const __u32mul = (a, b) => Math.imul(a, b) >>> 0;

const __u32div = (a, b) => (b === 0 ? __fail(\"divByZero\") : Math.trunc(a / b) >>> 0);

const __u32mod = (a, b) => (b === 0 ? __fail(\"divByZero\") : a % b >>> 0);

const __bigdiv = (a, b) => (b === 0n ? __fail(\"divByZero\") : a / b);

const __bigmod = (a, b) => (b === 0n ? __fail(\"divByZero\") : a % b);

const __strcmp = (a, b) => {
  const x = Array.from(a);
  const y = Array.from(b);
  const n = Math.min(x.length, y.length);
  for (let i = 0; i < n; i++) {
    const d = x[i].codePointAt(0) - y[i].codePointAt(0);
    if (d !== 0) return d < 0 ? -1 : 1;
  }
  return x.length === y.length ? 0 : x.length < y.length ? -1 : 1;
};

// === は参照を比べるので、構築子の値と配列には使えない。
const __eq = (a, b) => {
  if (a === b) return true;
  if (typeof a !== \"object\" || typeof b !== \"object\" || a === null || b === null) return false;
  if (Array.isArray(a) || Array.isArray(b)) {
    return (
      Array.isArray(a) &&
      Array.isArray(b) &&
      a.length === b.length &&
      a.every((x, i) => __eq(x, b[i]))
    );
  }
  const keys = Object.keys(a);
  return (
    keys.length === Object.keys(b).length &&
    keys.every((k) => Object.hasOwn(b, k) && __eq(a[k], b[k]))
  );
};

// 範囲外の添字は undefined ではなく失敗にする。undefined はサブセットに存在しない。
const __at = (xs, i) =>
  Number.isSafeInteger(i) && i >= 0 && i < xs.length
    ? xs[i]
    : __fail(\"indexOutOfBounds\");"

def Module.render (m : Module) : String :=
  "// Generated by leants. Do not edit.\n\n"
    ++ runtime ++ "\n\n"
    ++ String.intercalate "\n\n" (m.funcs.map Func.render) ++ "\n"

partial def tsType : Core.Ty → String
  | .bool => "boolean"
  | .int53 => "number"
  | .uint32 => "number"
  | .string => "string"
  | .bigint => "bigint"
  | .named n => n
  | .option t => "Option<" ++ tsType t ++ ">"
  | .result ok err => "Result<" ++ tsType ok ++ ", " ++ tsType err ++ ">"
  | .array t => "readonly " ++ tsType t ++ "[]"

private def renderCtor (c : Core.CtorDef) : String :=
  let fields := c.fields.map fun f => s!"; readonly {f.name}: {tsType f.ty}"
  "{ readonly tag: \"" ++ c.name ++ "\"" ++ String.join fields ++ " }"

private def declareType (t : Core.TypeDef) : String :=
  match t.ctors.map renderCtor with
  | [only] => "export type " ++ t.name ++ " = " ++ only ++ ";"
  | ctors => "export type " ++ t.name ++ " =\n  | " ++ String.intercalate "\n  | " ctors ++ ";"

def declareFunc (d : Core.Decl) : String :=
  let params := d.params.map fun p => p.name ++ ": " ++ tsType p.ty
  "export declare function " ++ d.name ++ "(" ++ String.intercalate ", " params ++ "): "
    ++ tsType d.ret ++ ";"

/-- `Option` と `Result` は組み込みなので、宣言も常に添える。型は消えるため未使用でも害はない。 -/
private def builtinTypes : String :=
"export type Option<T> =
  | { readonly tag: \"none\" }
  | { readonly tag: \"some\"; readonly value: T };

export type Result<T, E> =
  | { readonly tag: \"ok\"; readonly value: T }
  | { readonly tag: \"error\"; readonly error: E };"

def renderDts (p : Core.Program) : String :=
  let sections :=
    [builtinTypes] ++ p.types.map declareType ++ p.decls.map declareFunc
  "// Generated by leants. Do not edit.\n\n" ++ String.intercalate "\n\n" sections ++ "\n"

end LeanTs.Js
