import LeanTs.Json
import LeanTs.Core

/-!
# Js

出力する JavaScript の AST と ESM / `.d.ts` プリンタ。

括弧は優先順位を見ずに常に付ける。優先順位表はコンパイラの信頼ベースに載る一方、Phase 1 では
何も買わない。読みやすい出力は Phase 3 の課題。
-/

namespace LeanTs.Js

inductive Expr where
  | num (i : Int)
  | bigLit (i : Int)
  | str (s : String)
  | bool (b : Bool)
  | ident (name : String)
  | unary (op : String) (e : Expr)
  | binary (op : String) (lhs rhs : Expr)
  | cond (c t e : Expr)
  | call (callee : String) (args : List Expr)
  | arrowCall (params : List String) (body : Expr) (args : List Expr)
  deriving Inhabited

inductive Stmt where
  | const (name : String) (val : Expr)
  | ret (e : Expr)
  deriving Inhabited

structure Func where
  name : String
  params : List String
  body : List Stmt
  doc : String
  deriving Inhabited

structure Module where
  funcs : List Func
  deriving Inhabited

partial def Expr.render : Expr → String
  | .num i => toString i
  | .bigLit i => toString i ++ "n"
  | .str s => "\"" ++ escapeString s ++ "\""
  | .bool b => if b then "true" else "false"
  | .ident name => name
  | .unary op e => "(" ++ op ++ e.render ++ ")"
  | .binary op lhs rhs => "(" ++ lhs.render ++ " " ++ op ++ " " ++ rhs.render ++ ")"
  | .cond c t e => "(" ++ c.render ++ " ? " ++ t.render ++ " : " ++ e.render ++ ")"
  | .call callee args => callee ++ "(" ++ String.intercalate ", " (args.map Expr.render) ++ ")"
  | .arrowCall params body args =>
    "((" ++ String.intercalate ", " params ++ ") => " ++ body.render ++ ")("
      ++ String.intercalate ", " (args.map Expr.render) ++ ")"

def Stmt.render : Stmt → String
  | .const name val => "  const " ++ name ++ " = " ++ val.render ++ ";"
  | .ret e => "  return " ++ e.render ++ ";"

def Func.render (f : Func) : String :=
  let header := if f.doc.isEmpty then "" else "/** " ++ f.doc ++ " */\n"
  header ++ "export function " ++ f.name ++ "(" ++ String.intercalate ", " f.params ++ ") {\n"
    ++ String.intercalate "\n" (f.body.map Stmt.render) ++ "\n}"

/-- 生成コードが呼ぶ実行時ヘルパ。JS と Lean で答えが割れる演算をここに閉じ込めてある。 -/
def runtime : String :=
"const __fail = (code) => {
  const error = new Error(code);
  error.code = code;
  throw error;
};

// Int53 は数学的な整数なので -0 を残さない。JS では 0 - 0 も -4 % 2 も -0 になる。
const __i53 = (x) =>
  Number.isSafeInteger(x) ? (x === 0 ? 0 : x) : __fail(\"int53Overflow\");

const __i53div = (a, b) =>
  b === 0 ? __fail(\"divByZero\") : Number(BigInt(a) / BigInt(b));

const __i53mod = (a, b) => (b === 0 ? __fail(\"divByZero\") : __i53(a % b));

const __u32div = (a, b) => (b === 0 ? __fail(\"divByZero\") : Math.trunc(a / b) >>> 0);

const __u32mod = (a, b) => (b === 0 ? __fail(\"divByZero\") : a % b >>> 0);

const __bigdiv = (a, b) => (b === 0n ? __fail(\"divByZero\") : a / b);

const __bigmod = (a, b) => (b === 0n ? __fail(\"divByZero\") : a % b);

const __strcmp = (a, b) => {
  const x = Array.from(a);
  const y = Array.from(b);
  const n = Math.min(x.length, y.length);
  for (let i = 0; i < n; i++) {
    const d = x[i].codePointAt(0) - y[i].codePointAt(0);
    if (d !== 0) return d < 0 ? -1 : 1;
  }
  return x.length === y.length ? 0 : x.length < y.length ? -1 : 1;
};"

def Module.render (m : Module) : String :=
  "// Generated by leants. Do not edit.\n\n"
    ++ runtime ++ "\n\n"
    ++ String.intercalate "\n\n" (m.funcs.map Func.render) ++ "\n"

def tsType : Core.Ty → String
  | .bool => "boolean"
  | .int53 => "number"
  | .uint32 => "number"
  | .string => "string"
  | .bigint => "bigint"

def declareFunc (d : Core.Decl) : String :=
  let params := d.params.map fun p => p.name ++ ": " ++ tsType p.ty
  "export declare function " ++ d.name ++ "(" ++ String.intercalate ", " params ++ "): "
    ++ tsType d.ret ++ ";"

def renderDts (p : Core.Program) : String :=
  "// Generated by leants. Do not edit.\n\n"
    ++ String.intercalate "\n\n" (p.decls.map declareFunc) ++ "\n"

end LeanTs.Js
