import LeanTs.Render
import LeanTs.Js

/-!
# SourceMap

生成した `index.js` から `.leants` ソースへの source map。

対応づけは関数単位。式の中まで追わないのは、Core の項に位置情報を持たせていないため。スタックトレースが
どの関数のどの宣言に対応するかは分かる。
-/

namespace LeanTs

private def base64 : String :=
  "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"

private def base64Char (n : Nat) : String :=
  (base64.get? ⟨n⟩).map String.singleton |>.getD "A"

/-- source map の可変長数値。符号を最下位ビットに置き、5 ビットずつ下位から並べる。 -/
partial def vlq (value : Int) : String :=
  let unsigned := if value < 0 then ((-value).toNat * 2) + 1 else value.toNat * 2
  let rec go (n : Nat) (acc : String) : String :=
    let digit := n % 32
    let rest := n / 32
    if rest == 0 then acc ++ base64Char digit
    else go rest (acc ++ base64Char (digit + 32))
  go unsigned ""

structure Mapping where
  generatedLine : Nat
  sourceLine : Nat

/-- 各行ぶんのグループを `;` で区切る。列は毎行 0 に戻り、ソース行は直前からの差分で書く。 -/
def encodeMappings (totalLines : Nat) (mappings : List Mapping) : String :=
  let rec go (line : Nat) (prevSource : Int) (acc : List String) : List String :=
    if line ≥ totalLines then acc
    else
      match mappings.find? (·.generatedLine == line) with
      | some m =>
        let source := Int.ofNat m.sourceLine
        go (line + 1) source (acc ++ [vlq 0 ++ vlq 0 ++ vlq (source - prevSource) ++ vlq 0])
      | none => go (line + 1) prevSource (acc ++ [""])
  String.intercalate ";" (go 0 0 [])

def sourceMapJson (sourceName : String) (source : Core.Source)
    (totalLines : Nat) (mappings : List Mapping) : Json :=
  .obj [
    ("version", .num 3),
    ("file", .str "index.js"),
    ("sources", .arr [.str sourceName]),
    ("sourcesContent", .arr [.str source.text]),
    ("names", .arr []),
    ("mappings", .str (encodeMappings totalLines mappings))
  ]

/-- 生成した JS のテキストと、各関数が何行目から始まるか。 -/
structure Emitted where
  text : String
  funcLines : List (String × Nat)

private def countLines (s : String) : Nat := (s.splitOn "\n").length

/-- `export function` が本体の何行目に出るか。JSDoc を付けると先頭がずれるので、行を数える。 -/
private def signatureOffset (f : Js.Func) : Nat :=
  ((f.render.splitOn "\n").findIdx? (·.startsWith "export function")).getD 0

def emitModule (m : Js.Module) : Emitted :=
  let header := "// Generated by leants. Do not edit.\n\n" ++ Js.runtime ++ "\n\n"
  let start := countLines header - 1
  let (text, funcs) := m.funcs.foldl (init := (header, [])) fun (text, funcs) f =>
    let line := start + countLines text - countLines header + signatureOffset f
    (text ++ f.render ++ "\n\n", funcs ++ [(f.name, line)])
  { text := text ++ "//# sourceMappingURL=index.js.map\n", funcLines := funcs }

def sourceMapFor (p : Core.Program) (emitted : Emitted) (sourceName : String) : Json :=
  let source := p.source
  let mappings := emitted.funcLines.filterMap fun (name, line) =>
    (source.declLines.find? (·.1 == name)).map fun (_, sourceLine) =>
      { generatedLine := line, sourceLine : Mapping }
  sourceMapJson sourceName source (countLines emitted.text) mappings

end LeanTs
